### ISSUE TITLE
wrong command[bug]:  

### ISSUE THREAD

**Issue by WillGatto** [invertase/flutterfire_cli#102]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

flutterfire_cli 0.2.4.

### Firebase Tools version

...

### Flutter Doctor Output

[√] Flutter (Channel stable, 3.0.3, on Microsoft Windows [versÆo 10.0.19044.1889], locale pt-BR)
    • Flutter version 3.0.3 at C:\Users\zione\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (9 weeks ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
    • Android SDK at C:\Users\zione\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 31.0.0-rc5
    • ANDROID_HOME = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Android Studio
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÆo 10.0.19044.1889]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 104.0.5112.81
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.63

[√] HTTP Host Availability
    • All required HTTP hosts are available

### Description

at https://firebase.flutter.dev/docs/cli ... 
I've lost a day on this:     dart pub global activate flutterfire_cli . 
All environment variables have been set by my own and so on untill I decided to change the command to:   
flutter pub global activate flutterfire_cli
I think it's worth to have this command also shown for future users, so they won't waste time like myself. Thanks in advance.

### Steps to reproduce

run        flutter pub global activate flutterfire_cli

### Expected behavior

download, build and install CLI

**Comment by russellwheatley** [comment]
Documentation now shows correct way of installing FlutterFire CLI.
