### ISSUE TITLE
[bug]:  Wrong link to documentation in readme (?)

### ISSUE THREAD

**Issue by Albert221** [invertase/flutterfire_cli#106]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

-

### Firebase Tools version

-

### Flutter Doctor Output

-

### Description

The _Documentation_ link in README points to https://firebase.flutter.dev/docs/cli/.

But this website states: 

> NOTICE
> 
> This page is archived and might not reflect the latest version of the FlutterFire plugins. You can find the latest information on firebase.google.com:
> 
> https://firebase.google.com/docs/flutter/setup

Should it be updated to https://firebase.google.com/docs/flutter/setup then? Or is the linked documentation up-to-date and the notice is there by mistake?

### Steps to reproduce

-

### Expected behavior

-

**Comment by superiorsd10** [comment]
@Albert221 Can I work on this issue?

**Comment by bhattabhi013** [comment]
PLease close this issue as it no longer exists.

**Comment by Albert221** [comment]
It still does exist

**Comment by superiorsd10** [comment]
> It still does exist

Please assign it to me then.

**Comment by bhattabhi013** [comment]
[This](https://github.com/invertase/flutterfire_cli/pull/113) fixes it.
