### ISSUE TITLE
[bug]:  

### ISSUE THREAD

**Issue by SHOAIBAHMED12842** [invertase/flutterfire_cli#108]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.2.6

### Firebase Tools version

10.42

### Flutter Doctor Output

[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Version 10.0.19042.1889], locale en-US)
    • Flutter version 3.0.4 at C:\Users\msiraj005\Downloads\flutter_windows_3.0.4-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (3 months ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\msiraj005\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.11.16)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.11.32602.291
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.71.2)
    • VS Code at C:\Users\msiraj005\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.1889]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 105.0.5195.102
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 105.0.1343.33

[√] HTTP Host Availability
    • All required HTTP hosts are available

### Description

The CLI throws an error that 'git' is not recognized as an internal or external command, although i take necessary steps to install flutterfire CLI using command npm install -g firebase-tools / by standalone process.It make an error that this file cannnot be installed due to risk issues.

### Steps to reproduce

flutterfire configure

'git' is not recognized as an internal or external command,
operable program or batch file.
i Found 0 Firebase projects.
FirebaseCommandException: An error occured on the Firebase CLI when attempting to run a command.
COMMAND: firebase --version
ERROR: The FlutterFire CLI currently requires the official Firebase CLI to also be installed, see https://firebase.google.com/docs/cli#install_the_firebase_cli for how to install it.

### Expected behavior

When running  npm install -g firebase-tools command the CLI should properly install firebasetools.

### Screenshots

![Capture1](https://user-images.githubusercontent.com/46914029/191189205-7a25b085-f9cf-4e5e-b3ef-520cf1d66ec4.JPG)

**Comment by russellwheatley** [comment]
This is a problem with your environment setup and trying to install Firebase CLI. Not a FlutterFire CLI issue. This is the [relevant repository](https://github.com/firebase/firebase-tools).
