### ISSUE TITLE
request:  Add 'contributing.md'.

### ISSUE THREAD

**Issue by bhattabhi013** [invertase/flutterfire_cli#111]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command

NA

### Description

I expect this repository to have a `contributing.md` that includes guidelines and how to get started.

### Reasoning

It'll help to increase the contribution to this project.

**Comment by Anikalp1** [comment]
Please assign this to me

**Comment by bhattabhi013** [comment]
Hi @Anikalp1,
I'm new here as well. Currently, I'm working on this issue.

**Comment by Anikalp1** [comment]
is this issue assigned to you @bhattabhi013

**Comment by Kaushalrr006** [comment]
Please 
assign me this task

**Comment by syedzubeen** [comment]
Is this done or still open?

**Comment by Kaushalrr006** [comment]
To be done
