### ISSUE TITLE
request:  add code of conduct

### ISSUE THREAD

**Issue by akebu6** [invertase/flutterfire_cli#114]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

A code of conduct helps contributors know how they are to conduct themselves as well as to interact with other contributors. This will include all the guidelines and rules, (GitHub offers some examples of Code of Conduct)

### Reasoning

The repo should have a code of conduct on how contributors are to conduct themselves as well as to interact with other contributors

**Comment by biswadeep25** [comment]
Please add hacktoberfest label to this issue.
