### ISSUE TITLE
[bug]:  Flutterfire configure throwing an unhandled exception

### ISSUE THREAD

**Issue by noodles** [invertase/flutterfire_cli#115]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.2.6

### Firebase Tools version

11.0.1

### Flutter Doctor Output

[✓] Flutter (Channel stable, 3.3.3, on macOS 12.6 21G115 darwin-x64, locale en)
    • Flutter version 3.3.3 on channel stable at
      /usr/local/Caskroom/flutter/2.5.1/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (12 days ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/hallrichard/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.72.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • L10 (mobile)       • 27271FQHN00133                       • android-arm64
      • Android 13 (API 33)
    • iPhone 11 (mobile) • 839EB847-866A-48BF-939D-480DFBDCC875 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 12.6 21G115 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 106.0.5249.103

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

### Description

I'm getting an "Unhandled exception" when I run ```flutterfire configure``` on my Flutter project.
```
$ flutterfire configure               
i Found 9 Firebase projects.                                                    
✔ Select a Firebase project to configure your Flutter application with · fatal-demo (Fatal Demo) 
? Which platforms should your configuration support (use arrow keys & space to s✔ Which platforms should your configuration support (use arrow keys & space to select)? · android, ios 
i Firebase android app com.example.cli_test is not registered on Firebase project fatal-demo.
i Registered a new Firebase android app on Firebase project fatal-demo.         
i Firebase ios app com.example.cliTest is not registered on Firebase project fatal-demo.
i Registered a new Firebase ios app on Firebase project fatal-demo.             
? The files android/build.gradle & android/app/build.gradle will be updated to apply Firebase configuration and gradle build plugins. Do you want to continue? (✔ The files android/build.gradle & android/app/build.gradle will be updated to apply Firebase configuration and gradle build plugins. Do you want to continue? · yes 
Unhandled exception:
Exception: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- xcodeproj (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'

#0      ConfigCommand.run (package:flutterfire_cli/src/commands/config.dart:517:11)
<asynchronous suspension>
#1      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#2      main (file:///Users/hallrichard/.pub-cache/hosted/pub.dartlang.org/flutterfire_cli-0.2.6/bin/flutterfire.dart:57:5)
<asynchronous suspension>
```

### Steps to reproduce

1. Create a new flutter app 
```
$ flutter create cli_bug_demo
$ cd cli_bug_demo
```
2. Add Firebase crashlytics plugin 
```
$ flutter pub add firebase_crashlytics
```
3. Run Flutterfire CLI, select project that has worked previously & select iOS & Android platforms
```
$ flutterfire configure
```

### Expected behavior

```firebase_options.dart file``` is successfully created in my project folder and there are no exceptions or errors shown on the command line

### Screenshots

<img width="570" alt="Screen Shot 2022-10-10 at 10 24 17 pm" src="https://user-images.githubusercontent.com/183972/194860780-e4d1da1d-3c85-475d-b87d-dc8f62da6366.png">
<img width="666" alt="Screen Shot 2022-10-10 at 10 55 52 pm" src="https://user-images.githubusercontent.com/183972/194860900-60854b66-f705-4cb3-b092-2bb532f86a35.png">
<img width="571" alt="Screen Shot 2022-10-10 at 10 58 49 pm" src="https://user-images.githubusercontent.com/183972/194861733-c92b6f40-5f01-42f5-ab45-b2b495b8a606.png">

### Additional context and comments

This only began occurring after I upgrade from v0.2.2+2.

I have reproduced this issue on existing apps where the CLI has worked before as well as on new Flutter apps.

**Comment by noodles** [comment]
After restarting my Mac and trying ```flutterfire configure``` again:

```
Unhandled exception:
FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501:7)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36:10)
#3      JsonDecoder.convert (dart:convert/json.dart:612:36)
#4      FirebaseAndroidOptions.projectIdFromFileContents (package:flutterfire_cli/src/firebase/firebase_android_options.dart:29:29)
#5      FirebaseAndroidGradlePlugins.applyGoogleServicesPlugin (package:flutterfire_cli/src/firebase/firebase_android_gradle_plugins.dart:101:50)
<asynchronous suspension>
#6      FirebaseAndroidGradlePlugins.apply (package:flutterfire_cli/src/firebase/firebase_android_gradle_plugins.dart:240:5)
<asynchronous suspension>
```
<img width="568" alt="Screen Shot 2022-10-10 at 11 12 42 pm" src="https://user-images.githubusercontent.com/183972/194863800-f2961f8f-286f-4d0d-a231-110fd500d9a1.png">

**Comment by noodles** [comment]
I am experiencing the same issue with v0.2.5 and v0.2.2+2 so I suspect this is not a bug but an issue with my system. Any help would still be appreciated.

**Comment by noodles** [comment]
So maybe I'm not as good at searching existing issues as I need to be:

[FormatException: Unexpected character when calling flutterfire configure](https://github.com/invertase/flutterfire_cli/issues/27)

I will add any further comments there.

**Comment by SATOKOKI645** [comment]
1. Update to RubyGems:
```shell
gem update --system
```
2. install xcodeproj
```shell
gem install xcodeproj
```
3. Configure FlutterFire
```shell
flutterfire configure
```
