### ISSUE TITLE
[bug]: `--android-app-id` flag does not update value  

### ISSUE THREAD

**Issue by rddewan** [invertase/flutterfire_cli#120]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.2.6

### Firebase Tools version

11.14.2

### Flutter Doctor Output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale en-TH)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.72.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

### Description

command not found: --android-package-name=dev.rdewan.ecomApp.development

flutterfire config \
  --project=flutter-ecomapp-dev-c7f8b \
  --out=lib/core/firebase/firebase_options_dev.dart \
  --ios-bundle-id=dev.rdewan.ecomApp.development \     
  --android-package-name=dev.rdewan.ecomApp.development  

### Steps to reproduce

change to --android-app-id but it does not wrok 

### Expected behavior

should create a correct add with android id

**Comment by Lyokone** [comment]
Hello @rddewan,
I just tried locally, can you try properly with 
```sh
flutterfire configure --android-package-name=com.your.name
```

To check?

**Comment by rddewan** [comment]
@Lyokone it does not work , it use the default android package name , but since i have a flavor setup it will have a suffix based on flavor

**Comment by NoizyCr1cket** [comment]
I am having this same issue, but I found a workaround (explained at the bottom).

I run this command
```sh
flutterfire config \
  --project=baseball-bluebook-dev \
  --platforms=android,ios,web
  --out=lib/firebase_options_dev.dart \
  --ios-bundle-id=com.baseballbluebook.ios.dev \
  --android-app-id=com.baseballbluebook.mobile.dev \
  --android-package-name=com.baseballbluebook.mobile.dev \
  --web-app-id=baseball_bluebook_web
```

And the output is 
```
i Found 2 Firebase projects. Selecting project baseball-bluebook-dev.                                              
i Selected platforms: android,ios,web
i Firebase android app com.baseballbluebook.mobile is not registered on Firebase project baseball-bluebook-dev.    
i Registered a new Firebase android app on Firebase project baseball-bluebook-dev.   
```

You can see it ignored my input and used the name `com.baseballbluebook.mobile` to create the new Android app registration on my Firebase project, which would prevent me from connecting to the right project. It seems like it was detecting that name from my `applicationId` under the `defaultConfig` section in `android/app/build.gradle`, because it was this:
```gradle
    defaultConfig {
        applicationId "com.baseballbluebook.mobile"
```

## Workaround
After changing the `applicationId` value to `com.baseballbluebook.mobile.dev` and re-running my command above, I got it to use the correct value, and then I just changed it back afterwards.

**Comment by NoizyCr1cket** [comment]
You are missing some backslashes in your command. Try this instead:
```sh
flutterfire config \
--project=flutter-ecomapp-dev-c7f8b \
--out=lib/core/firebase/firebase_options_dev.dart \
--ios-bundle-id=dev.rdewan.ecomApp.development \
--android-package-name=dev.rdewan.ecomApp.development
```

**Comment by russellwheatley** [comment]
I was not able to reproduce, and as @NoizyCr1cket pointed out, you are missing backslashes.
