### ISSUE TITLE
[bug]:  configure command not updating build.gradle files

### ISSUE THREAD

**Issue by mrquentin** [invertase/flutterfire_cli#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.2.6+1

### Firebase Tools version

11.15.0

### Flutter Doctor Output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.6, on Microsoft Windows [Version 10.0.22623.870], locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.6)
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
[✓] VS Code (version 1.72.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!

### Description

I am on a windows machine and created an flutter app. I then wanted to setup firebase for it so I ran flutterfire configure. After selecting the project and platform, the command successfully create the ios and android app in firebase but never updates the android/build.gradle nor the android/app/build.gradle.

Result: my app never starts as the firebase initialise app doesn't work.

### Steps to reproduce

1. Run `flutter create reproduce_bug --org "com.test"`
2. Run `cd reproduce_bug`
3. Run `flutter pub add firebase_core` (installed version is 2.1.1)
4. Run `flutterfire configure`
5. Select the firebase project
6. Select platform android and ios

### Expected behavior

The flutterfire configure command is expected to update the build.gradle file (android/build.gradle and android/app/build.gradle). 

![image](https://user-images.githubusercontent.com/32539717/198412223-0e42069a-c832-4777-8d87-6a5485203f1b.png)
cf : https://youtu.be/vtGCteFYs4M?t=12612

### Screenshots

Here is the output i get from the flutterfire command which is different from the one seen in expected behaviour

![image](https://user-images.githubusercontent.com/32539717/198412477-ea461563-79af-472f-8210-82fee6e4faff.png)

**Comment by OutdatedGuy** [comment]
Same behaviour is seen by me. On my windows machine, the `flutterfire cli` doesn't add necessary package needed code in the `build.gradle` file.

But on my macbook, the package required code is added to `build.gradle` file.

Package required code:
```gradle
// START: FlutterFire Configuration
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'com.google.firebase.firebase-perf'
// END: FlutterFire Configuration
```

and

```gradle
// START: FlutterFire Configuration
classpath 'com.google.gms:google-services:4.3.10'
classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'
classpath 'com.google.firebase:perf-plugin:1.4.1'
// END: FlutterFire Configuration
```

My `flutterfire_cli` package version is `0.2.6+1`

**Comment by Hauglid** [comment]
I'm getting the same behaviour on Mac.

**Comment by anroswart** [comment]
No setup happening in either of the `build.gradle` files for me when running `flutterfire configure`. I'm on version `0.2.7`.

**Comment by M123-dev** [comment]
Same here no native file is changed, not on Windows and not using WSL

**Comment by russellwheatley** [comment]
Could everyone confirm that this is only occurring on their windows machine? Thanks.

**Comment by Hauglid** [comment]
@russellwheatley  Does not work on mac.

**Comment by russellwheatley** [comment]
@Hauglid - any chance you could provide the build.gradles you have (omitting anything sensitive but keep formatting the exact same)?

The dependencies portion is what I'm interested in seeing for `android/build.gradle`:

e.g.
```gradle
    dependencies {
        classpath 'com.android.tools.build:gradle:7.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
```

and for `android/app/build.gradle`:

```gradle
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

```

**Comment by alidev0** [comment]
New Project, same issue.

**Comment by DanPetras** [comment]
@russellwheatley The important information is that default flutter project structure for Android changed from the previous format. Now it uses also settings.gradle file along with the two build.gradle files as it used to be.

I added comments where I'd expect CLI to add required plugins.

Also worth noting is that in default project created in Android Studio, the `plugins { id "some.plugin" version "x.y.z" apply false ... }` is located in the top module build.gradle file but flutter puts it in the settings.gradle, so it seems that it can work in both locations.

Top module build.gradle file:
```
buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
```

app module build.gradle file:
```
plugins {
    id "com.android.application"
    id "kotlin-android"
    id "dev.flutter.flutter-gradle-plugin"
    # I would expect firebase plugins to be added here
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

android {
    namespace "com.example.app"
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "com.example.app"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdkVersion flutter.minSdkVersion
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        debug {
            versionNameSuffix 'd'
        }
        release {
            minifyEnabled true
            shrinkResources true
        }
    }
}

flutter {
    source '../..'
}

dependencies {}
```

settings.gradle file:
```
pluginManagement {
    def flutterSdkPath = {
        def properties = new Properties()
        file("local.properties").withInputStream { properties.load(it) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        return flutterSdkPath
    }
    settings.ext.flutterSdkPath = flutterSdkPath()

    includeBuild("${settings.ext.flutterSdkPath}/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }

    plugins {
        id "dev.flutter.flutter-gradle-plugin" version "1.0.0" apply false
    }
}

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.3.0" apply false
    # I would expect firebase plugins to be added here with "apply false"
}

include ":app"
```

**Comment by DanPetras** [comment]
@alidev0 Is #251 related?

**Comment by alidev0** [comment]
> @alidev0 Is #251 related?

even before that flutterfire_cli did not properly put the necessary code lines when using a windows machine, but it was working on mac. Now it does not work on either, yes probably because of #251 .

**Comment by alidev0** [comment]
@DanPetras i did it by using android studio for that and that refer to this: https://github.com/firebase/flutterfire/issues/11912 for a fix after.

**Comment by russellwheatley** [comment]
@alidev0 - use the dev release, it has the fix:
```
dart pub global activate flutterfire_cli 0.3.0-dev.19 --overwrite
```

**Comment by LimaneGaya** [comment]
@russellwheatley i keep getting this error using flutterfire_cli 0.3.0-dev.19

TimeoutException after 0:00:15.000000: Future not completed

**Comment by easypku** [comment]
Same happens to me on Mac. Using the latest flutterfire_cli version (or 19) did not work.
