### ISSUE TITLE
[bug]:  error while running `flutterfire configure`

### ISSUE THREAD

**Issue by mckn** [invertase/flutterfire_cli#127]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.2.6.+1

### Firebase Tools version

11.15.0

### Flutter Doctor Output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.5, on macOS 13.0 22A380 darwin-x64, locale sv-SE)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.72.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

### Description

The CLI throws the following error if I run the following command `flutterfire configure`.

```bash
i Found 1 Firebase projects.                                                                                    
✔ Select a Firebase project to configure your Flutter application with · ***** (*****)                
✔ Which platforms should your configuration support (use arrow keys & space to select)? · android, ios          
i Firebase android app ***** registered.                                                        
i Firebase ios app ***** registered.                                                            
Unhandled exception:
Exception: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- xcodeproj (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'

#0      ConfigCommand.run (package:flutterfire_cli/src/commands/config.dart:517:11)
<asynchronous suspension>
#1      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#2      main (file:///Users/*****/.pub-cache/hosted/pub.dartlang.org/flutterfire_cli-0.2.6+1/bin/flutterfire.dart:57:5)
<asynchronous suspension>
```

### Steps to reproduce

1. Run command `flutterfire configure`
2. You will see the error mentioned above.

### Expected behavior

When running the CLI everything should be configured correctly

**Comment by jianshangquan** [comment]
Run following command solve issue on my machine "Mac M1"
```bash
sudo gem install cocoapods && pod install
```
I found similar behavior from source [stackoverflow](https://stackoverflow.com/questions/19674550/cocoapods-loaderror-no-such-file-to-load)

**Comment by mckn** [comment]
So it turns out it wasn't this CLI it is cocoapods. So I reinstalled the `xcodeproj` by running `gem install xcodeproj` which worked.

**Comment by aweife** [comment]
For anyone that can't use `sudo gem install xcodeproj` for some reason, you are likely using the macOS's ruby. Install ruby with homebrew and then do `gem install xcodeproj` as an alternative.

See this: https://mac.install.guide/faq/do-not-use-mac-system-ruby/index.html

**Comment by santoshakil** [comment]
> 

This works for me !!! Thanks....

**Comment by erlangparasu** [comment]
may relate with this issue https://github.com/invertase/flutterfire_cli/issues/30

**Comment by dolva2000** [comment]
Pour tous ceux qui ne peuvent pas l'utiliser` sudo gem install xcodeproj` pour une raison quelconque, vous utilisez probablement le rubis de macOS. Installez Ruby avec homebrew, puis faites-le `gem install xcodeproj `comme alternative.

Voir ceci : https://mac.install.guide/faq/do-not-use-mac-system-ruby/index.html

**Comment by BenCodeurr** [comment]
> Pour tous ceux qui ne peuvent pas l'utiliser` sudo gem install xcodeproj` pour une raison quelconque, vous utilisez probablement le rubis de macOS. Installez Ruby avec homebrew, puis faites-le `gem install xcodeproj `comme alternative.
> 
> Voir ceci : https://mac.install.guide/faq/do-not-use-mac-system-ruby/index.html

Ceci m'a aidé. Merci!

**Comment by gabrielscr** [comment]
> So it turns out it wasn't this CLI it is cocoapods. So I reinstalled the `xcodeproj` by running `gem install xcodeproj` which worked.

MABOY! Thanks, solved in M3 Pro.

**Comment by enny007** [comment]
> For anyone that can't use `sudo gem install xcodeproj` for some reason, you are likely using the macOS's ruby. Install ruby with homebrew and then do `gem install xcodeproj` as an alternative.
> 
> See this: https://mac.install.guide/faq/do-not-use-mac-system-ruby/index.html

Thank you so much sir...This saved me so much time

**Comment by DerKellerBlock** [comment]
Thanks solved also my problem!

**Comment by iamkem** [comment]
> So it turns out it wasn't this CLI it is cocoapods. So I reinstalled the `xcodeproj` by running `gem install xcodeproj` which worked.

Solved for me, many tks.

**Comment by apm-thomas-meyer** [comment]
Thanks, works for me, too (M1 Pro)

**Comment by ShaunZh** [comment]
> For anyone that can't use `sudo gem install xcodeproj` for some reason, you are likely using the macOS's ruby. Install ruby with homebrew and then do `gem install xcodeproj` as an alternative.
> 
> See this: https://mac.install.guide/faq/do-not-use-mac-system-ruby/index.html

Thanks, works for me, (M1)

**Comment by ashraf267** [comment]
> gem install xcodeproj

Thanks, this worked!
