### ISSUE TITLE
[bug]:  Option ios-bundle-id is mandatory.

### ISSUE THREAD

**Issue by rymesaint** [invertase/flutterfire_cli#134]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

latest version

### Firebase Tools version

11.16.1

### Flutter Doctor Output

[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0.1 22A400 darwin-x64, locale en-ID)
    • Flutter version 3.3.8 on channel stable at /Users/ridwanfauzan/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (13 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ridwanfauzan/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (4 available)
    • iPhone 13 Pro (mobile) • 0DC746C8-271E-41C7-93D7-6D7FDA8C7753 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • iPhone 14 Pro (mobile) • 4107541B-1987-4A9C-8BD7-ECE90C47581D • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS
      13.0.1 22A400 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google
      Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

### Description

I want to generate android only without any ios but it gives me error **Option ios-bundle-id is mandatory.**

### Steps to reproduce

Run flutterfire configure -t $FLUTTER_FIRE_TOKEN -y --platforms=android -a com.isolution.***_mobile.dev

### Expected behavior

The CLI should generate firebase file

### Screenshots

<img width="1019" alt="Screenshot 2022-11-22 at 20 16 02" src="https://user-images.githubusercontent.com/4441045/203323311-b89df3df-8822-4238-9369-95fbea4fb531.png">

**Comment by barilki** [comment]
Some updates???

**Comment by arthuRHD** [comment]
I'm not even targetting iOS and I'm getting this error.

[You can see my full pipeline logs here](https://gist.github.com/arthuRHD/ec12c8395f455074c3ac014cca328414)

**Comment by arthuRHD** [comment]
maintainers are sleeping or what

**Comment by arthuRHD** [comment]
Can someone merge my PR please ?

**Comment by arthuRHD** [comment]
Thanks @russellwheatley for maintaining this repository ❤️
