### ISSUE TITLE
[docs]:  GoogleService-Info.plist is not created

### ISSUE THREAD

**Issue by EArminjon** [invertase/flutterfire_cli#148]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.3.0-dev.15

### Firebase Tools version

11.23.1

### Flutter Doctor Output

[√] Flutter (Channel stable, 3.3.4, on Microsoft Windows [version 10.0.19045.2486], locale fr-FR)
    • Flutter version 3.3.4 on channel stable at C:\Users\engue\fvm\versions\3.3.4
    • Upstream repository https://github.com/flutter/flutter.git                  
    • Framework revision eb6d86ee27 (5 months ago), 2022-10-04 22:31:45 -0700     
    • Engine revision c08d7d5efc                                                  
    • Dart version 2.18.2                                                         
    • DevTools version 2.15.0                                                     

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at D:\Android                                                                               
    • Platform android-33, build-tools 33.0.1                                                                 
    • Java binary at: C:\Users\engue\.jdks\corretto-11.0.17\bin\java                                          
    • Java version OpenJDK Runtime Environment Corretto-11.0.17.8.1 (build 11.0.17+8-LTS)                     
    • All Android licenses accepted.                                                                          
                                                                                                              
[√] Chrome - develop for the web                                                                              
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe                                   
                                                                                                              
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.18)                               
    • Visual Studio at D:\dev                                                                                 
    • Visual Studio Community 2019 version 16.11.32802.440                                                    
    • Windows 10 SDK version 10.0.22621.0                                                                     
                                                                                                              
[!] Android Studio (not installed)                                                                            
    • Android Studio not found; download from https://developer.android.com/studio/index.html                 
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
                                                                                                              
[√] IntelliJ IDEA Ultimate Edition (version 2022.3)                                                           
    • IntelliJ at C:\Users\engue\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\223.8617.56                 
    • Flutter plugin version 72.1.4                                                                           
    • Dart plugin version 223.8617.8                                                                          
                                                                                                              
[√] Connected device (3 available)                                                                            
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [version 10.0.19045.2486]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.122
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 109.0.1518.78

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

### Description

```
flutterfire configure --project=my-project-test --out=lib/entrypoints/lyonfoot/firebase_options.dart --android-out=/android/app/src/clienta/google-services.json --ios-bundle-id=ClientA--android-package-name=myenterpriseflutter.clienta --ios-out=/ios/Firebase/clienta/GoogleService-Info.plist --yes
```

File GoogleService-Info.plist is not created. I see an empty firebase.json created  :
Its content : 

```
{"flutter":{"platforms":{"ios":{"buildConfigurations":{},"targets":{},"default":{}},"macos":{"buildConfigurations":{},"targets":{},"default":{}}}}}
```

For Android all seems to work as expected. (Should this script change the build.gradle ?)

### Steps to reproduce

Flutter create a new project
Create 2 android apps and 2 ios apps on Firebase console (clientA & clientB)

Run the flutterfire configure above.
See that GoogleService-Info.plist is not created.

### Expected behavior

GoogleService-Info.plist should be created

**Comment by EArminjon** [comment]
Maybe because I'm under windows, didn't see this behavior on MacOS.

**Comment by russellwheatley** [comment]
It won't work because it is on windows. But perhaps we can add a log to inform developers.
