### ISSUE TITLE
`flutterfire configure` unusable with large number of Firebase projects

### ISSUE THREAD

**Issue by domesticmouse** [invertase/flutterfire_cli#15]
Attempting to use `flutterfire configure` against an account with a large number of Firebase projects lands the user in an unusable project selector.

**Comment by Salakar** [comment]
Have seen this as well locally - will need to swap out the library we use for prompts since this is an issue with that.

Will take a look, thanks for the report

**Comment by russellwheatley** [comment]
The workaround is to select the project via the command:
```
flutterfire configure --project=<PROJECT_NAME>
```
