### ISSUE TITLE
[bug]:  google-services.json not created when using  --android-out argument

### ISSUE THREAD

**Issue by egyleader** [invertase/flutterfire_cli#155]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

 ver 0.3.0-dev.16

### Firebase Tools version

11.23.1

### Flutter Doctor Output

[✓] Flutter (Channel stable, 3.7.5, on macOS 13.2.1 22D68 darwin-arm64, locale
    en-EG)
    • Flutter version 3.7.5 on channel stable at /Users/egyleader/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (6 days ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/egyleader/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/egyleader/Library/Android/sdk
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk-19.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 19.0.1+10-21)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave
      Browser

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (4 available)
    • M2010J19SG (mobile)     • d06deb780221                             •
      android-arm64  • Android 12 (API 31)
    • Ahmed’s iPhone (mobile) • 031ae2de087ef4c80bc376cdc4f77a12c7f22e2e • ios
      • iOS 14.4.2 18D70
    • macOS (desktop)         • macos                                    •
      darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)            • chrome                                   •
      web-javascript • Brave Browser 110.1.48.171
    ! Error: Ahmed’s iPhone is busy: Fetching debug symbols for Ahmed’s iPhone.
      Xcode will continue when Ahmed’s iPhone is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

### Description

when running this command :

```bash
flutterfire configure --project=projectName --out=lib/firebase/options/firebase_options.dart --android-package-name=com.dkilo.walk --android-out=android/app/src/production/google-services.json --ios-build-config=Debug-production  --ios-out=ios/config/production/GoogleService-Info.plist --ios-bundle-id=com.example.app 
```

the google-services.json is not created at all , but when running same command without --android-out argument it is created in default folder . 

### Steps to reproduce

1. run command with --android-out option and see there is no google-services.json file
2. remove this option and see it created in android/app/src/main

### Expected behavior

google-services.json is created in the specified folder .

**Comment by theachoem** [comment]
I got the same issue!

**Comment by russellwheatley** [comment]
This was a bug in that version, try the latest:
```
dart pub global activate flutterfire_cli 0.3.0-dev.18 --overwrite 
```
and it should solve your problem.
