### ISSUE TITLE
[bug]: flutterfire-upload: Can only run iOS app with Flutter - Xcode manual run is broken

### ISSUE THREAD

**Issue by EArminjon** [invertase/flutterfire_cli#156]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.3.0-dev.16

### Firebase Tools version

9.23.1

### Flutter Doctor Output

[✓] Flutter (Channel stable, 3.3.4, on macOS 13.1 22C65 darwin-arm, locale fr-FR)
    • Flutter version 3.3.4 on channel stable at /Users/enguerrandarminjon/fvm/versions/3.3.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (5 months ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/enguerrandarminjon/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /Users/enguerrandarminjon/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/enguerrandarminjon/Library/Android/sdk
    • Java binary at: /Users/enguerrandarminjon/Library/Java/JavaVirtualMachines/corretto-1.8.0_322/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-8.322.06.1 (build 1.8.0_322-b06)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Users/enguerrandarminjon/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 18F69A87-6204-4E19-8C4F-ED3FB8291A22 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 110.0.5481.177

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

### Description

When i add the firebase upload script bellow (generated by flutterfire configure) 

```bash
#!/bin/bash
PATH=${PATH}:/Users/enguerrandarminjon/Documents/Softwares/flutter/bin:/Users/enguerrandarminjon/.pub-cache/bin
flutterfire upload-crashlytics-symbols --upload-symbols-script-path=$PODS_ROOT/FirebaseCrashlytics/upload-symbols --debug-symbols-path=${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME} --info-plist-path=${SRCROOT}/${BUILT_PRODUCTS_DIR}/${INFOPLIST_PATH} --platform=ios --apple-project-path=${SRCROOT} --target=Runner
```

I got following issue : 

```
Command PhaseScriptExecution failed with a nonzero exit code
```

This issue happen only if i run the app directly through Xcode (but it's important to did that for watchos development for example).

### Steps to reproduce

flutterfire configure
launch xcode
run app inside xcode

### Expected behavior

No issue

### Additional context and comments

My app have 4 targets and many build configuration (flavors) like Debug-clienta, Debug-clientb, Release-clienta, etc. 
![Capture d’écran 2023-03-01 à 22 35 23](https://user-images.githubusercontent.com/37028599/222270185-b7e49fb6-b259-42f7-a972-d5d440319a32.png)

**Comment by ebsangam** [comment]
Getting same error with, dart command not found.

**Comment by EArminjon** [comment]
> Getting same error with, dart command not found.

Your issue is totally different than mine, please open a dedicated issue.

**Comment by KoheiKanagu** [comment]
Are you using `--obfuscate` by any chance?
That was the cause of the issue for me. 
https://github.com/firebase/flutterfire/issues/10507#issuecomment-1556174938

**Comment by EArminjon** [comment]
> Are you using `--obfuscate` by any chance? That was the cause of the issue for me. [firebase/flutterfire#10507 (comment)](https://github.com/firebase/flutterfire/issues/10507#issuecomment-1556174938)

no i didn't use it?

**Comment by russellwheatley** [comment]
Thanks for the report, @EArminjon. I was able to reproduce this and currently looking into it.

**Comment by EArminjon** [comment]
> Thanks for the report, @EArminjon. I was able to reproduce this and currently looking into it.

Amazing 😍

**Comment by EArminjon** [comment]
@russellwheatley  was not able before to find the logs of this error, now i can share : 

```
/Users/enguerrandarminjon/.pub-cache/bin/flutterfire: line 8: dart: command not found
Command PhaseScriptExecution failed with a nonzero exit code
```

The source script : 

```
#!/bin/bash
PATH=${PATH}:/Users/enguerrandarminjon/.pub-cache/bin
flutterfire bundle-service-file --plist-destination=${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app --build-configuration=${CONFIGURATION} --platform=ios --apple-project-path=${SRCROOT}
```

Btw, hop you will soon replace the home path by the proper variable `${HOME}` :) !

**Comment by russellwheatley** [comment]
Ok, this issue is fixed already in the FFCLI repo: https://github.com/invertase/flutterfire_cli/pull/175. Could you please track this issue as I will announce the latest FFCLI dev release there: https://github.com/invertase/flutterfire_cli/issues/14. Thanks, @EArminjon
