### ISSUE TITLE
Flutter Fire CLI cannot create IOS bundle id more than 12 character

### ISSUE THREAD

**Issue by nyomansunima** [invertase/flutterfire_cli#16]
Today I try to initialize my new project, and when I configure to the ios bundle and type my bundle id "com.sonibble.cawis" I cannot type again after type "com.sonibble.c".

BTW my default ios bundle in folder ios "not yet setup"

Detail about my platform:
- Mac OS M1 (Monterey)

**Comment by nyomansunima** [comment]
Btw, I can solve it by adding --ios-bundle-id argument. But the confirm dialog is more important. I hope this issue will be improved

**Comment by dryasbk** [comment]
I manage to use ios bundle ID by:
`flutterfire configure icom.example.myapp`

So add i followed by your ios bundle ID and was longer than 7 characters.

From [FlutterFire CLI Commands](https://firebase.flutter.dev/docs/cli/#configure)

**Comment by russellwheatley** [comment]
Yes, just use the `--ios-bundle-id` to specify your bundle ID.
