### ISSUE TITLE
[bug]:  Unable to use flutterfire when using embedded flutter as submodule in android app

### ISSUE THREAD

**Issue by ProvMitraDora** [invertase/flutterfire_cli#169]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.2.0

### Firebase Tools version

10.4.2

### Flutter Doctor Output

Unable to use flutterfire when using embedded flutter as submodule in android app

### Description

Unable to use flutterfire when using embedded flutter as submodule in android app

### Steps to reproduce

flutterfire configure

NoFlutterPlatformsSelectedException: You must select at least one Flutter platform to generate your configuration for.

### Expected behavior

Should configure crashlytics inside flutter app

**Comment by russellwheatley** [comment]
You're going to have to provide a repro. Please use the latest version as you're using a very old version.

Latest:
```
dart pub global activate flutterfire_cli 0.3.0-dev.18 --overwrite 
```

**Comment by russellwheatley** [comment]
Closing out as issue is stale.
