### ISSUE TITLE
Add clientId to web member of DefaultFirebaseOptions

### ISSUE THREAD

**Issue by nickmeinhold** [invertase/flutterfire_cli#17]
The use case is being able to pass the clientId when creating `GoogleSignIn`, avoiding having to add a meta tag to `index.html`.  We can add the value to a Dart file ourselves of course but I thought the clientId might be a valid addition to the web member of DefaultFirebaseOptions, and would make things a bit easier and cleaner.

**Comment by Salakar** [comment]
Firebase does not provide a clientId option for web sdks so there's nowhere for us to retrieve this from as far as I know

**Comment by nickmeinhold** [comment]
I see, thanks for the explanation
