### ISSUE TITLE
[bug]:  NoFlutterPlatformsSelectedException: You must select at least one Flutter platform to generate your configuration for.

### ISSUE THREAD

**Issue by droidmitra** [invertase/flutterfire_cli#170]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.2.0

### Firebase Tools version

10.4.2

### Flutter Doctor Output

NoFlutterPlatformsSelectedException: You must select at least one Flutter platform to generate your configuration for.

### Description

NoFlutterPlatformsSelectedException: You must select at least one Flutter platform to generate your configuration for.

### Steps to reproduce

NoFlutterPlatformsSelectedException: You must select at least one Flutter platform to generate your configuration for.

### Expected behavior

NoFlutterPlatformsSelectedException: You must select at least one Flutter platform to generate your configuration for.

### Screenshots

NoFlutterPlatformsSelectedException: You must select at least one Flutter platform to generate your configuration for.

**Comment by russellwheatley** [comment]
Try the latest version, you are using a very old version:

Latest:
```
dart pub global activate flutterfire_cli 0.3.0-dev.18 --overwrite 
```
