### ISSUE TITLE
Error while configuring firebase cli in flutter project ? 

### ISSUE THREAD

**Issue by harryandroiddev** [invertase/flutterfire_cli#180]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### CLI Version

0.2.7

### Firebase Tools version

12.0.1

### Flutter Doctor Output

[✓] Flutter (Channel stable, 3.10.0, on macOS 13.0 22A8380 darwin-arm64
    (Rosetta), locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.78.2)
[✓] Connected device (3 available)
[✓] Network resources

### Description

After running the command flutterfire configure it throws the following error .

Unhandled exception:
FormatException: Unexpected character (at line 96, character 1)
{
^

#0 _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
https://github.com/firebase/flutterfire/pull/1 _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:848:48)
https://github.com/firebase/flutterfire/pull/2 _parseJson (dart:convert-patch/convert_patch.dart:35:10)
https://github.com/firebase/flutterfire/pull/3 JsonDecoder.convert (dart:convert/json.dart:610:36)
https://github.com/firebase/flutterfire/pull/4 runFirebaseCommand (package:flutterfire_cli/src/firebase.dart:95:25)

https://github.com/firebase/flutterfire/issues/5 getProjects (package:flutterfire_cli/src/firebase.dart:114:20)

https://github.com/firebase/flutterfire/issues/6 ConfigCommand._selectFirebaseProject (package:flutterfire_cli/src/commands/config.dart:300:24)

https://github.com/firebase/flutterfire/issues/7 ConfigCommand.run (package:flutterfire_cli/src/commands/config.dart:390:37)

https://github.com/firebase/flutterfire/issues/8 CommandRunner.runCommand (package:args/command_runner.dart:212:13)

https://github.com/firebase/flutterfire/issues/9 main (file:///Users/harwinder/.pub-cache/hosted/pub.dev/flutterfire_cli-0.2.7/bin/flutterfire.dart:57:5)

### Steps to reproduce

1. firebase login  (success)
2. flutterfire configure 

### Expected behavior

It should add the firebase project and configuration to the project but not works as expected and throws the above error.
On running firebase login after login succesffully it also show the below error in screen shot .
### Screenshots
<img width="567" alt="Screenshot 2023-05-24 at 10 10 59 AM" src="https://github.com/invertase/flutterfire_cli/assets/57495358/bbc6881c-11d0-488f-afe0-ccd4d1f1e1f1">

_No response_

**Comment by sussertod891015** [comment]
I got the same issue...
It should be noted that I used a proxy and set the following settings in the .zshrc file
`export http_proxy="http://localhost:15236"`
`export https_proxy="http://localhost:15236"`
Only when I changed the proxy to a global proxy, I can executed `fireBase login` successfully, but executing `flutterfire configure` can't be successful, can someone solve this problem, has been bothering me for a long time.

**Comment by raveganeshdevlekar** [comment]
i am getting same error
