### ISSUE TITLE
[bug]:  FlutterFire is not working with 3.10

### ISSUE THREAD

**Issue by nilsreichardt** [invertase/flutterfire_cli#181]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.2.7

### Firebase Tools version

11.24.1

### Flutter Doctor Output

```
Flutter 3.10.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d3d8effc68 (8 days ago) • 2023-05-16 17:59:05 -0700
Engine • revision b4fb11214d
Tools • Dart 3.0.1 • DevTools 2.23.1
```

### Description

```
NilsMBP13M14:ankigpt nils$ flutterfire configure
Can't load Kernel binary: Invalid kernel binary format version.
Building package executable... (1.9s)
Failed to build flutterfire_cli:flutterfire:
../../.pub-cache/hosted/pub.dev/quiver-3.1.0/lib/src/collection/treeset.dart:45:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get iterator;
  ^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/quiver-3.1.0/lib/src/collection/treeset.dart:49:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get reverseIterator;
  ^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/quiver-3.1.0/lib/src/collection/treeset.dart:58:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> fromIterator(V anchor,
  ^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/quiver-3.1.0/lib/src/collection/treeset.dart:742:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get iterator => _AvlTreeIterator._(this);
  ^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/quiver-3.1.0/lib/src/collection/treeset.dart:746:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get reverseIterator =>
  ^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/quiver-3.1.0/lib/src/collection/treeset.dart:751:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> fromIterator(V anchor,
  ^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/quiver-3.1.0/lib/src/collection/treeset.dart:894:38: Error: Type 'BidirectionalIterator' not found.
class _AvlTreeIterator<V> implements BidirectionalIterator<V> {
                                     ^^^^^^^^^^^^^^^^^^^^^
```

### Steps to reproduce

1. Download Flutter 3.10 (e.g. `3.10.2`)
2. Install `flutterfire`
3. Run `flutterfire configure`

### Expected behavior

CLI should work

### Additional context and comments

Switching to Flutter v3.7.12 worked as a workaround.

**Comment by marcucio** [comment]
same error here

**Comment by nohe427** [comment]
1. What OS are you on?
2. What happens if you update to the latest firebase-tools?
3. What happens if you update to the latest flutter release?
4. Which processor are you using?

I tried reproducing the issue described but could not do it on an M1 macOS machine using flutter 3.10.3.

**Comment by Juliotati** [comment]
@nohe427  I have the same issue. But i'll update to the same latest versions you have and try again.

**Comment by Ishadir** [comment]
Same error here

**Comment by nilsreichardt** [comment]
Using the dev version is another workaround:

```sh
dart pub global activate flutterfire_cli 0.3.0-dev.16
```

**Comment by nilsreichardt** [comment]
cc: @russellwheatley

**Comment by Ishadir** [comment]
Hi, I don't know if this will work for everyone, but in my case, I reverted all the changes I made while adding flutterfire, then i created a new branch just for this try, did a:

`flutter pub upgrade --major-versions `
`flutter pub outdated` just to review.

in the `build.gradle`

```
buildscript {
     ext.kotlin_version = '1.7.10'

dependencies {
         classpath 'com.android.tools.build:gradle:7.2.0'
``` 


My `build.gradle` at the `app `level is like this (for information only):

```
android {
     compileSdkVersion 33

defaultConfig {
         minSdkVersion 21
         targetSdkVersion 32
``` 


in my `gradle-wrapper.properties` (android\gradle\wrapper\gradle-wrapper.properties)

```
distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-all.zip
``` 

I did a `flutter clean`.

then i tried again
`flutter pub add firebase_crashlytics`
`flutterfire configure`

I put `yes `to the prompts where it overrides gradle files.

And I tried running a debug build and it worked for me.

**Comment by russellwheatley** [comment]
Hey folks, I'll take a look at this soon enough. We've merged some substantial changes that needs to go through a review process before we release. Once this is done, I'll circle back to this and a few other bugs on my radar. Thanks for your patience 🙏
