### ISSUE TITLE
request:  Override existing GoogleServie-plist

### ISSUE THREAD

**Issue by EArminjon** [invertase/flutterfire_cli#183]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command

flutterfire configure --override-google-service=yes

### Description

"Your GoogleService-Info.plist already exists, skipping write..."

Could be useful to be able to override / rewrite them through CLI.

### Reasoning

Migration my flavors APP to use an other Firebase project. 
Android google-service.json files were well rewrite but not the iOS one because of "Your GoogleService-Info.plist already exists, skipping write..."

**Comment by russellwheatley** [comment]
Will be out in the next release: https://github.com/invertase/flutterfire_cli/pull/174.
