### ISSUE TITLE
not showing newly created project [bug]:  

### ISSUE THREAD

**Issue by vishnuprasad0** [invertase/flutterfire_cli#187]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.2.7

### Firebase Tools version

12.4.7

### Flutter Doctor Output

PS C:\learn flutter\instagram_clone> flutter doctor -v
[√] Flutter (Channel stable, 3.10.2, on Microsoft Windows [Version 10.0.22621.1992], locale en-IN)
    • Flutter version 3.10.2 on channel stable at C:\Users\vishn\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (3 months ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\vishn\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • Java binary at: C:\Program Files\Java\jdk-17.0.7\bin\java
    • Java version Java(TM) SE Runtime Environment (build 17.0.7+8-LTS-224)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.6.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33712.159
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.81.0)
    • VS Code at C:\Users\vishn\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.70.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1992]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 115.0.1901.200

[√] Network resources
    • All expected network resources are available.

### Description

runed "flutterfire --configure" to continue setup with an already created project with GUI.
but that newly created project not found in cli. another old project is showing and option to create new project was also there.

tried logout again and login that not fixed.
then tried to create new project with existing name at that moment it showed error its an already existing project name. but that project was not shown in 'Flutterfire --configure'
 

### Steps to reproduce

create a new project from web or firebase GUI
then run 'flutterfire --configure'

### Expected behavior

then it need to show that newly created projects but its not showing .

### Screenshots

![Screenshot (58)](https://github.com/invertase/flutterfire_cli/assets/82352446/7e2183db-ce46-4450-811b-ad51dd981e49)
![Screenshot (57)](https://github.com/invertase/flutterfire_cli/assets/82352446/9cb285e0-dec7-4e3f-996c-2a5d1883e06b)
![Screenshot (59)](https://github.com/invertase/flutterfire_cli/assets/82352446/a4870c78-2de1-4a03-bc84-ef61d5c66d29)

### Additional context and comments

in my case look at the screenshots for clarification it says there is an existing project 'instagram-clone-5f512'
then why not it is showing while running 'flutterfire --configure'

**Comment by russellwheatley** [comment]
Install the latest FlutterFire version:
```
dart pub global activate flutterfire_cli 0.3.0-dev.18 --overwrite
```

Run configure with the project set:
```
flutterfire configure --project=instagram-clone-5f512
```

does that solve your problem?

**Comment by russellwheatley** [comment]
Closing as this issue is stale.
