### ISSUE TITLE
flutterfire CLI doesn't seem to find my firebase install

### ISSUE THREAD

**Issue by jeremyhalin** [invertase/flutterfire_cli#19]
I've just installed Firebase CLI with standalone bin. 
I've placed the binary in `C:\firebasecli\firebase-tools-instant-win.exe` and added the directory to my PATH.

I can now access firebase cli through my terminal and `firebase-tools-instant-win`.
Everything works fine, I was able to login and to list my projects.

But when I do a `flutterfire configure` here is what I got :

```bash
> flutterfire configure
i Found 0 Firebase projects. Selecting project project-name-4e1f6.
FirebaseCommandException: An error occured on the Firebase CLI when attempting to run a command.
COMMAND: firebase --version 
ERROR: The FlutterFire CLI currently requires the official Firebase CLI to also be installed, see https://firebase.google.com/docs/cli#install_the_firebase_cli for how to install it.

> firebase --version
10.0.1

>
```

I did go through flutterfire cli souce code and I've seen that it's just trying to do a `firebase --version` which is working on my side : 
```bash
> firebase --version
10.0.1
```

What did I miss?

**Comment by Zohaib-Dev-Engr** [comment]
I am also getting the same error.

**Comment by jeremyhalin** [comment]
I found a workaround as [mentioned here](https://stackoverflow.com/a/70417084), placing the firebase CLI binary in your project and renaming it to `firebase.exe` works fine...

**Comment by allasca** [comment]
> I found a workaround as [mentioned here](https://stackoverflow.com/a/70417084), placing the firebase CLI binary in your project and renaming it to `firebase.exe` works fine...

not work with me.
PS D:\Flutter\tebak> flutterfire configure
⠙ Fetching available Firebase projects...
Unhandled exception:
FormatException: Unexpected character (at character 1)
#
^

**Comment by jeremyhalin** [comment]
@allasca Your error doesn't seem to be related to mine. You had same error as me before?

**Comment by allasca** [comment]
> @allasca Your error doesn't seem to be related to mine. You had same error as me before?

I dont know, maybe same.
already re-install flutter_cli still not work.
already renamed to firebase.exe and copy to project folder, not work.
maybe I need to do it manually

**Comment by chonghorizons** [comment]
I had a similar issue (#33), but it was solved with the two commands here: https://github.com/invertase/flutterfire_cli/issues/27#issuecomment-1002965081

Maybe that will help.

**Comment by jonscoresby** [comment]
I got this error as well, none of the options discussed here fixed it for me. I ended up just installing using npm.
