### ISSUE TITLE
[bug]:  Installing FlutterFire: Package not available (authorization failed).

### ISSUE THREAD

**Issue by msaleh1383** [invertase/flutterfire_cli#198]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.2.7

### Firebase Tools version

12.5.2

### Flutter Doctor Output

[√] Flutter (Channel stable, 3.13.1, on Microsoft Windows [Version 10.0.22621.2215], locale en-US)
    • Flutter version 3.13.1 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (9 days ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at F:\Android\android-sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = F:\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.4.1)
    • Visual Studio at F:\Microsoft Visual Studio\2022\Enterprise
    • Visual Studio Enterprise 2022 version 17.4.33110.190
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2023.1.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code, 64-bit edition (version 1.71.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2215]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 116.0.5845.141
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 116.0.1938.62

[√] Network resources
    • All expected network resources are available.

• No issues found!

### Description

When I run the following command (after Firebase login, based on Firebase docs) for connecting my flutter project to Firebase, the command occurs with the error: Package not available (authorization failed).

dart pub global activate flutterfire_cli

Flutter ver.: 3.13.1
Dart ver.: 3.1.0

### Steps to reproduce

1. Install Firebase CLI and
   Run Command "firebase login"
2. I logged into my account
3. Run Command "dart pub global activate flutterfire_cli"
4. Giving "Resolving dependencies..."
5. Giving error "Package not available (authorization failed)."

### Expected behavior

This error, if is from your side, please fix that immediately...

### Screenshots

![image](https://github.com/invertase/flutterfire_cli/assets/37481850/11fba80a-6d2e-4e16-ad46-6c548ede60d2)

**Comment by russellwheatley** [comment]
This is not happening from our side, this is from `pub.dev` where the package resides. It could be a number of issues but it isn't solved here.
