### ISSUE TITLE
[bug]:  cli is not generating iosclientid key in firebase_options.dart file

### ISSUE THREAD

**Issue by edimarvirtual** [invertase/flutterfire_cli#208]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.2.7

### Firebase Tools version

11.19.0

### Flutter Doctor Output

[✓] Flutter (Channel stable, 3.10.0, on macOS 12.6.5 21G531 darwin-x64, locale pt-BR)
    • Flutter version 3.10.0 on channel stable at /Users/edimargotardo/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (4 months ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/edimargotardo/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6.5 21G531 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.179

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Description

When executing the `flutterfire configure` command everything works normally, but I noticed that it is no longer generating the `androidClientId` and `iosClientId` Keys, consequently, for this reason when I download the `GoogleService-Info.plist` file, the same it is coming without the `REVERSED_CLIENT_ID` key that I need to add to the `Info.plist` file

Since I use Firebase phone authentication, I need these keys for my app to be authorized

*NOTE: I didn't do any type of update, not even in the sources, dependencies or binaries, and until 2 days ago everything was generating normally*

### Steps to reproduce

1. run `flutterfire configure`
2. select firebase project
3. select (android, iOS and web platforms)
4. If the option to replace the files appears, answer yes
5. check the `firebase_options.dart` file, and see if it generated the `iosClientId` key for the ios platform

### Expected behavior

for it to generate the `iosClientId` key for the ios platform in the `firebase_options.dart` file

### Screenshots

![Captura de Tela 2023-09-10 às 09 58 21](https://github.com/invertase/flutterfire_cli/assets/12664670/4dd0df9a-6e65-4e37-91ad-7e71c35f242d)
It is currently generating like this 👆

![Captura de Tela 2023-09-10 às 10 08 54](https://github.com/invertase/flutterfire_cli/assets/12664670/8577fb8a-2bb5-4cdb-bd23-46e9ea6278ba)
But before it generated normally 👆
(this file was 2 days ago, in the same environment with no updates to the sources or binaries)

**Comment by russellwheatley** [comment]
I've just tested this on the latest dev release:
```
dart pub global activate flutterfire_cli 0.3.0-dev.18 --overwrite
```
The `iosClientId` is written in the `firebase_options.dart` file.

**Comment by sanlanka** [comment]
This means that the sign in providers are not configured. Once you configure them, run flutterfire configure again and you should see the ClientId. Cheers!
