### ISSUE TITLE
[bug]: Flutterfire -v command shows incorrect version number

### ISSUE THREAD

**Issue by jlin5** [invertase/flutterfire_cli#213]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.3.0-dev.18

### Firebase Tools version

12.3.1

### Flutter Doctor Output

[✓] Flutter (Channel stable, 3.13.3, on macOS 13.5.2 22G91 darwin-x64, locale en-US)
    • Flutter version 3.13.3 on channel stable at /Users/jlin/fvm/versions/3.13.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (6 days ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

### Description

The `flutterfire -v` command displays the wrong CLI version for version 0.3.0-dev.17 and 0.3.0-dev.18.

### Steps to reproduce

Download flutterfire_cli version 0.3.0-dev.18
```
dart pub global activate flutterfire_cli 0.3.0-dev.18 --overwrite
```
Run the version command
```
flutterfire -v
```
The result shows 0.3.0-dev.16 instead of 0.3.0-dev.18. This is also happening in 0.3.0-dev.17.

### Expected behavior

When running `flutterfire -v` I expect the correct CLI version to be displayed.

### Additional context and comments

I noticed that the version in **packages/flutterfire_cli/lib/version.g.dart** for is still set to 0.3.0-dev.16.

**Comment by russellwheatley** [comment]
I was also able to reproduce 👍

**Comment by russellwheatley** [comment]
This has been fixed in the latest dev release. Please install by running the following:

```bash
dart pub global activate flutterfire_cli 0.3.0-dev.19 --overwrite
```
