### ISSUE TITLE
[bug]:  Flutterfire reconfigure not working

### ISSUE THREAD

**Issue by SherpaMiguel** [invertase/flutterfire_cli#214]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.3.0-dev.18

### Firebase Tools version

12.5.4

### Flutter Doctor Output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.5.2 22G91 darwin-arm64, locale es-ES)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.82.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

### Description

The "reconfigure" command is not working for me.

```
Failed to write ios "GoogleService-Info.plist" file write for default target (Runner). Please report this issue at:https://github.com/invertase/flutterfire_cli. Exception: type 'Null' is not a subtype of type 'String' in type cast
Unhandled exception:
type 'Null' is not a subtype of type 'String' in type cast
#0      Reconfigure._updateServiceFile (package:flutterfire_cli/src/commands/reconfigure.dart:95:56)
#1      Reconfigure._updateAppleServiceFiles (package:flutterfire_cli/src/commands/reconfigure.dart:170:9)
<asynchronous suspension>
#2      Reconfigure.run (package:flutterfire_cli/src/commands/reconfigure.dart:402:7)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#4      main (file:///Users/miguel/.pub-cache/hosted/pub.dev/flutterfire_cli-0.3.0-dev.18/bin/flutterfire.dart:63:5)
<asynchronous suspension>
```

### Steps to reproduce

Run command `flutterfire reconfigure`

### Expected behavior

It fails and should not.

**Comment by russellwheatley** [comment]
Have you edited the `firebase.json` in the root of your project? If you have, this would be the reason why this is throwing an exception. The exception is occurring because there is no longer a property in your configuration for file output (`fileOutput` property). It is occurring for your apple (either macOS or iOS) configuration.

**Comment by russellwheatley** [comment]
Hey @gelas7, I'm going to need more details. Specifically, the properties in your `firebase.json` under the `flutter` object that caused this exception. Thanks.

**Comment by ryan-holder** [comment]
Hi @gelas7, I'm not sure about `flutterfire reconfigure`, but I was having problems running an app with a similar setup and seeing the same error `type 'Null' is not a subtype of type 'String' in type cast` in `flutterfire_cli/src/commands/bundle_service_file.dart:99:67` when debugging/building.

Changing the instances of `"serviceFileOutput"` to `"fileOutput"` allowed it to run. Not a solution by any means but may point to the cause. Has this property been renamed @russellwheatley?

**Comment by russellwheatley** [comment]
remove "default" and "targets" from ios configuration, perhaps?

**Comment by russellwheatley** [comment]
Thanks for confirming. Latest FFCLI dev release shouldn't write those empty objects anymore 👍
