### ISSUE TITLE
[bug]: PhaseScriptExecution FlutterFire: flutterfire upload-crashlytics-symbols fails when archive app on XcodeBuild

### ISSUE THREAD

**Issue by michaelsoliman1** [invertase/flutterfire_cli#216]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.3.0-dev.18

### Firebase Tools version

12.5.4

### Flutter Doctor Output

[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64, locale en-EG)
    • Flutter version 3.10.6 on channel stable at /Users/michael/Dev/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (9 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/michael/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.82.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Description

The exception only happens on Xcode Build, when I archive the app locally it works, I reconfigured all project (i use multiple flavors) and generated firebase.json file.

*note*: after updating to `0.3.18` i had to activate flutterfire in `ci_post_clone.sh` (below)
```
PhaseScriptExecution FlutterFire:\ \"flutterfire\ upload-crashlytics-symbols\" /Volumes/workspace/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/staging/IntermediateBuildFilesPath/Runner.build/Release-staging-iphoneos/Runner.build/Script-1C565E0404ECB51EC9F2AC70.sh (in target 'Runner' from project 'Runner')
    cd /Volumes/workspace/repository/apps/my-app/ios
    /bin/sh -c /Volumes/workspace/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/staging/IntermediateBuildFilesPath/Runner.build/Release-staging-iphoneos/Runner.build/Script-1C565E0404ECB51EC9F2AC70.sh

Unhandled exception:
Exception: 
#0      UploadCrashlyticsSymbols.run (package:flutterfire_cli/src/commands/upload_symbols.dart:315:7)
<asynchronous suspension>
#1      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#2      main (file:///Users/local/.pub-cache/hosted/pub.dev/flutterfire_cli-0.3.0-dev.18/bin/flutterfire.dart:63:5)
<asynchronous suspension>
Command PhaseScriptExecution failed with a nonzero exit code
```

firebase.json
```
{
    "flutter": {
        "platforms": {
            "android": {
                "buildConfigurations": {
                    "src/staging": {
                        "projectId": "my-app-staging",
                        "appId": "1:4084..",
                        "fileOutput": "android/app/src/staging/google-services.json"
                    },
                    "src/production": {
                        "projectId": "my-app-8c6c6",
                        "appId": "1:5619..",
                        "fileOutput": "android/app/src/production/google-services.json"
                    },
                    "src/development": {
                        "projectId": "my-app-dev",
                        "appId": "1:1446..",
                        "fileOutput": "android/app/src/development/google-services.json"
                    }
                }
            },
            "ios": {
                "buildConfigurations": {
                    "Release-staging": {
                        "projectId": "my-app-staging",
                        "appId": "1:4084..",
                        "uploadDebugSymbols": true,
                        "fileOutput": "ios/config/staging/GoogleService-Info.plist"
                    },
                    "Release-production": {
                        "projectId": "my-app-8c6c6",
                        "appId": "1:5619..",
                        "uploadDebugSymbols": true,
                        "fileOutput": "ios/config/production/GoogleService-Info.plist"
                    },
                    "Release-development": {
                        "projectId": "my-app-dev",
                        "appId": "1:1446..",
                        "uploadDebugSymbols": true,
                        "fileOutput": "ios/config/development/GoogleService-Info.plist"
                    }
                }
            },
            "dart": {
                "lib/firebase_options_staging.dart": {
                    "projectId": "my-app-staging",
                    "configurations": {
                        "android": "1:4084..",
                        "ios": "1:4084.."
                    }
                },
                "lib/firebase_options_production.dart": {
                    "projectId": "my-app-8c6c6",
                    "configurations": {
                        "android": "1:5619..",
                        "ios": "1:5619.."
                    }
                },
                "lib/firebase_options_development.dart": {
                    "projectId": "my-app-dev",
                    "configurations": {
                        "android": "1:1446..",
                        "ios": "1:1446.."
                    }
                }
            }
        }
    }
}

```
### ci_post_clone.sh
```
#!/bin/sh

# The default execution directory of this script is the ci_scripts directory.
cd $CI_WORKSPACE/apps/my-app # change working directory to the root of your cloned repo.

# Install Flutter using git.
git clone https://github.com/flutter/flutter.git --depth 1 -b 3.10.6 $HOME/flutter
export PATH="$PATH:$HOME/flutter/bin"

# Install Flutter artifacts for iOS (--ios), or macOS (--macos) platforms.
flutter precache --ios

# Install Flutter dependencies.
flutter pub get

# had to add this line
# Install FlutterFire cli
dart pub global activate flutterfire_cli 0.3.0-dev.18 --overwrite 

# Install CocoaPods using Homebrew.
HOMEBREW_NO_AUTO_UPDATE=1 # disable homebrew's automatic updates.
brew install cocoapods

# Install CocoaPods dependencies.
cd ios && pod install # run `pod install` in the `ios` directory.

exit 0

```

### Steps to reproduce

1- Add firebase_crashlytics
2- Run flutterfire configure (will add Build PhaseScript FlutterFire: "flutterfire upload-crashlytics-symbols")
3- build app on Xcode Cloud

### Expected behavior

archive succeed

**Comment by michaelsoliman1** [comment]
The archive was running on latest macOS version (Sonoma 14) when i changed it to macOS Ventura it worked, so it's probably a problem with the macOS version. Closing this as macOS Sonoma 14 is not released yet

**Comment by Finni123** [comment]
I get the same error. I am also working on macOS 14 and cannot easily change back to an older version. Is this something that will be fixed in the near future? The Sonoma beta is released by now, does the flutterfire cli not support it?

**Comment by LeonManolo** [comment]
> The archive was running on latest macOS version (Sonoma 14) when i changed it to macOS Ventura it worked, so it's probably a problem with the macOS version. Closing this as macOS Sonoma 14 is not released yet

I'm having the same issue, but I'm on macOS Ventura and using Xcode Version 15.2 (15C500b). Removing firebase_crashlytics does not help either. The strange thing is that I can run the app on my iPhone and the command `flutter build ios --release` also succeeds.

```
PhaseScriptExecution FlutterFire:\ \"flutterfire\ upload-crashlytics-symbols\" /Users/manolo/Library/Developer/Xcode/DerivedData/Runner-cvmsvoaljkttvlgxeswvdnlonomi/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Script-AEFB34E4D5463EF6C33198CD.sh (in target 'Runner' from project 'Runner')




Can't load Kernel binary: Invalid kernel binary format version.
FINE: Pub 2.18.5
ERR : flutterfire_cli as globally activated doesn't support Dart 2.18.5, try: dart pub global activate flutterfire_cli
FINE: Exception type: DataException
FINE: package:pub/src/utils.dart 531:36                      dataError
    | package:pub/src/global_packages.dart 383:9             GlobalPackages.find.<fn>
    | dart:collection                                        _LinkedHashMapMixin.forEach
    | package:pub/src/global_packages.dart 376:29            GlobalPackages.find
    | package:pub/src/command/global_run.dart 68:44          GlobalRunCommand.runProtected
    | package:pub/src/command.dart 189:45                    PubCommand.run.<fn>
    | dart:async                                             new Future.sync
    | package:pub/src/utils.dart 109:12                      captureErrors.wrappedCallback
    | package:stack_trace                                    Chain.capture
    | package:pub/src/utils.dart 122:11                      captureErrors
    | package:pub/src/command.dart 189:13                    PubCommand.run
    | package:args/command_runner.dart 209:27                CommandRunner.runCommand
    | package:dartdev/dartdev.dart 231:30                    DartdevRunner.runCommand
    | package:args/command_runner.dart 119:25                CommandRunner.run.<fn>
    | dart:async                                             new Future.sync
    | package:args/command_runner.dart 119:14                CommandRunner.run
    | package:dartdev/dartdev.dart 66:29                     runDartdev
    | /opt/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart 11:9  main
    | ===== asynchronous gap ===========================
    | dart:async                                             Future.catchError
    | package:pub/src/utils.dart 109:52                      captureErrors.wrappedCallback
    | package:stack_trace                                    Chain.capture
    | package:pub/src/utils.dart 122:11                      captureErrors
    | package:pub/src/command.dart 189:13                    PubCommand.run
    | package:args/command_runner.dart 209:27                CommandRunner.runCommand
    | package:dartdev/dartdev.dart 231:30                    DartdevRunner.runCommand
    | package:args/command_runner.dart 119:25                CommandRunner.run.<fn>
    | dart:async                                             new Future.sync
    | package:args/command_runner.dart 119:14                CommandRunner.run
    | package:dartdev/dartdev.dart 66:29                     runDartdev
    | /opt/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart 11:9  main
```

**Comment by pdkcoder** [comment]
I'm getting exactly the same issue today

**Comment by mahmudulhasancsedu5** [comment]
I was also facing the same problem while building my flutter iOS app, after upgrading to macOS 14 and flutter version  3.24.2. In my case flutterfire_cli was not installed. So after installing flutterfire_cli  inside project root folder, this issue resolved.

# _Install the CLI if not already done so_
**dart pub global activate flutterfire_cli**

# _Run the `configure` command, select a Firebase project and platforms_
**flutterfire configure**

If you already configure firebase project jut press ‘yes’ in next step.

**Comment by Gabriel-Eduardo-Cunha** [comment]
I fixed the issue on my local machine by running:
`dart pub global activate flutterfire_cli`
and then:
`flutterfire configure`

But in my github actions fastlane deploy, the same issue still happens:
```
The following build commands failed:
	PhaseScriptExecution FlutterFire:\ \"flutterfire\ upload-crashlytics-symbols\" /Users/runner/Library/Developer/Xcode/DerivedData/Runner-erjabulonldmywbnklbaahcbjotm/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Script-7867ED93261E30BE5474933C.sh (in target 'Runner' from project 'Runner')
```
It seens that github actions is not running at the latest XCode version. In my local machine XCode is at 16.0, but in the github actions XCode is 15.4.

I have no clue on how to fix that by now. How can I force XCode to be 16.0 on the github action macos machine?

**Comment by nehangTatvasoft** [comment]
I face the same issue when I configure flutterfire and firebase_crashlytics that Command PhaseScriptExecution failed with a nonzero exit code. After debugging I found that the Run script of Flutterfire Firebase crashlytic was not able to find the path of firebase.json. So I changed the path of the project location using Camelcase and restarted the project and it worked for me.

Follow the below steps

Change the project location path using Camelcase (e.g. user/flutter/project)
Run flutterfire configure
Run project in Xcode

**Comment by lidaloki** [comment]
I started seeing this issue again. When it popped up for the first time, running `flutterfire configure` helped, but not anymore. I'm pretty sure I have not changed any project settings.

**Comment by ThomasPorrmann** [comment]
Same problem here. Any solution?

**Comment by gstephinewings** [comment]
Issue is coming again. Any Solution?

**Comment by witchcraft2001** [comment]
Additionally, I’ve only been able to work around this by invoking the Crashlytics dSYM upload script directly. You can drop this into script place for `FlutterFire: "flutterfire upload-crashlytics-symbols"` (or something like that) build phase:
```
#!/bin/bash
if [ -z "$PODS_ROOT" ] || [ ! -d "$PODS_ROOT/FirebaseCrashlytics" ]; then
  echo "Warning: PODS_ROOT not found or FirebaseCrashlytics pod missing. Trying SPM path."
  DERIVED_DATA_PATH=$(echo "$BUILD_ROOT" | sed -E 's|(.*DerivedData/[^/]+).*|\1|')
  PATH_TO_CRASHLYTICS_UPLOAD_SCRIPT="${DERIVED_DATA_PATH}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run"
else
  PATH_TO_CRASHLYTICS_UPLOAD_SCRIPT="$PODS_ROOT/FirebaseCrashlytics/run"
fi

if [ ! -f "$PATH_TO_CRASHLYTICS_UPLOAD_SCRIPT" ]; then
    echo "error: Crashlytics native script not found at $PATH_TO_CRASHLYTICS_UPLOAD_SCRIPT"
    exit 1
fi

GSP_PATH="${PROJECT_DIR}/Runner/GoogleService-Info.plist"
if [ ! -f "$GSP_PATH" ]; then
    echo "error: GoogleService-Info.plist not found at $GSP_PATH"
    exit 1
fi

DSYM_PATH="${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}"
if [ ! -d "$DSYM_PATH" ]; then
    echo "error: dSYM file not found at $DSYM_PATH"
fi

echo "Attempting to run native Crashlytics script directly..."
"$PATH_TO_CRASHLYTICS_UPLOAD_SCRIPT" -gsp "$GSP_PATH" -p ios "$DSYM_PATH"

if [ $? -ne 0 ]; then
    echo "warning: Native Crashlytics script finished with non-zero exit code. Upload might have failed."
fi

echo "Native Crashlytics script execution initiated."
```
This successfully uploads the dSYM files, confirming that the root cause lies in flutterfire_cli’s own upload logic.

**Comment by karroze** [comment]
The "solution" above does not work with flavors, so it's pretty much useless
