### ISSUE TITLE
[bug]:  Module 'cloud_firestore' not found

### ISSUE THREAD

**Issue by srpushpendra** [invertase/flutterfire_cli#231]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.2.7

### Firebase Tools version

12.5.2

### Flutter Doctor Output

[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.1 23B81 darwin-x64, locale en-IN)
    • Flutter version 3.16.0 on channel stable at /Users/mt11-1065/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (3 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/mt11-1065/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (3 available)
    • Pushpendra’s iPhone (mobile) • adbca9d21d5fc744767a19b0660a6a87425777a8 • ios            • iOS 16.7.2 20H115
    • macOS (desktop)              • macos                                    • darwin-x64     • macOS 14.1.1 23B81 darwin-x64
    • Chrome (web)                 • chrome                                   • web-javascript • Google Chrome 119.0.6045.159
    ! Error: Pushpendra’s Apple Watch needs to connect to determine its availability. Check the connection between the device and its companion iPhone, and the
      connection between the iPhone and Xcode. Both devices may also need to be restarted and unlocked. (code 1)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Description

CLI work fine 
but when we build using Xcode then getting error like "Module 'cloud_firestore' not found"

### Steps to reproduce

all ok

### Expected behavior

all ok

### Screenshots

<img width="2048" alt="Screenshot 2023-11-19 at 11 09 09 AM" src="https://github.com/invertase/flutterfire_cli/assets/42764657/3b988b47-59eb-426c-bd8f-f7bb9dda5d89">

**Comment by russellwheatley** [comment]
This is nothing to do with FlutterFire CLI. Closing out. You might try running the project from VS code first before running in Xcode. i.e. `flutter run`.
