### ISSUE TITLE
request:  Add the ability to run flutterfire reconfigure at CI

### ISSUE THREAD

**Issue by AhmedLSayed9** [invertase/flutterfire_cli#232]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command

flutterfire reconfigure --token "$FIREBASE_TOKEN"

### Description

Running a firebase command in a CI system can be done using the --token flag.

The --token flag is already supported by `flutterfire configure` but we can't use it with `flutterfire reconfigure`.

### Reasoning

It's a bit tedious to write all the `flutterfire configure` commands at the CI while we can easily use `flutterfire reconfigure`.

**Comment by russellwheatley** [comment]
Hey @AhmedLSayed9 - There is already a hidden flag for passing the access token that should work: https://github.com/invertase/flutterfire_cli/blob/main/packages/flutterfire_cli/test/reconfigure_test.dart#L121-L126

Let me know how it goes and I'll update the code to make this a public flag. Thanks 🙏
