### ISSUE TITLE
[bug]:  `-web-app-id` if wrong after configuration

### ISSUE THREAD

**Issue by followthemoney1** [invertase/flutterfire_cli#238]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.3.0-dev.18

### Firebase Tools version

12.8.0

### Flutter Doctor Output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.6, on macOS 14.1.2 23B92 darwin-arm64, locale en-UA)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2022.3.1)
[✓] VS Code (version 1.84.0)
[✓] Connected device (2 available)
    ! Error: Browsing on the local area network for Dmitry’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

! Doctor found issues in 1 category.

### Description

I'm trying to fetch the Firebase configuration using CLI, and my web app id is correct. I've doubled it, but in the end cli plugin set up the wrong web app id

### Steps to reproduce

run command:
```sh
siteConfig=$(firebase --project "jh-mobile-$ENVIRONMENT" hosting:sites:get "$AFFILIATE_ROOT_SLUG-jh-$ENVIRONMENT" --json)
app_id_line=$(echo "$siteConfig" | grep '"appId"')
app_id=$(echo "$app_id_line" | sed 's/.*"appId": "\(.*\)".*/\1/')
echo "siteConfig: $siteConfig and webAppId: $app_id"

$DART_COMMAND pub global activate flutterfire_cli 0.3.0-dev.18 --overwrite

flutterfire configure  --verbose --platforms=web --project jh-mobile-$ENVIRONMENT --web-app-id=$app_id \
--overwrite-firebase-options
```

where web app id is specified so you can just run:
```
flutterfire configure  --verbose --platforms=web --project jh-mobile-$ENVIRONMENT --web-app-id=$app_id 
```

### Expected behavior

-web-app-id is correct

### Screenshots

![Untitled](https://github.com/invertase/flutterfire_cli/assets/8526612/00ef774e-20ee-463e-aadc-4454b48727b1)

**Comment by followthemoney1** [comment]
where application with right id is actually existed 
![image](https://github.com/invertase/flutterfire_cli/assets/8526612/610790b3-2dd4-48f1-bf7a-8db8adb7fed7)

**Comment by russellwheatley** [comment]
This has already been fixed but has not been released yet: https://github.com/invertase/flutterfire_cli/pull/225. Will try and get a release out next week 🙏
