### ISSUE TITLE
[bug]: "Unable to get file attributes for dSYM file at path" if iOS/macOS Product Name contains space

### ISSUE THREAD

**Issue by nilsreichardt** [invertase/flutterfire_cli#243]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.3.0-dev.18

### Firebase Tools version

13.0.1

### Flutter Doctor Output

```
[✓] Flutter (Channel stable, 3.16.3, on macOS 13.6 22G120 darwin-arm64 (Rosetta), locale en-DE)
    • Flutter version 3.16.3 on channel stable at /Users/nils/fvm/versions/3.16.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (3 days ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/nils/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2023.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
    • IntelliJ at /Users/nils/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.4345.14/IntelliJ
      IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.85.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.82.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • Nils’s iPhone (mobile) • 00008110-00042D6011D3801E • ios            • iOS 17.1.2 21B101
    • macOS (desktop)        • macos                     • darwin-arm64   • macOS 13.6 22G120 darwin-arm64 (Rosetta)
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 119.0.6045.199

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

### Description

I set up my macOS app with `flutterfire configure`. However, I'm unable to build my app because I get the following error message:

```
Unable to get file attributes for dSYM file at path "/Users/nils/Projects/sharezone/sharezone-app/app/build/macos/Build/Products/Debug-dev/dev Sharezone.app.dSYM/Contents/Resources/DWARF"
```

When I rename my Product Name to "devSharezone", it works.

### Steps to reproduce

1. Create a new Flutter macOS (or iOS) app
2. Open XCode
3. Go Build Settings
4. Search "Product Name"
5. Enter "dev Sharezone" (ensure you have a space in the name)

### Expected behavior

The build should work.

### Screenshots

![Screenshot 2023-12-09 at 13 15 09](https://github.com/invertase/flutterfire_cli/assets/24459435/9e3421f8-1f4e-4a40-88a8-357393190cce)

In this screenshot you can see it generated the "dev Sharezone.DSYM" but tries to do something in "dev". This is the Finder at the location `build/macos/Build/Products/Debug-dev`.

**Comment by russellwheatley** [comment]
@nilsreichardt - could you give me steps for a repro, please? I'm going to get a release out this week so would be nice to get this fix in for it 👍

**Comment by nilsreichardt** [comment]
I have already included steps to reproduce in the issue. Let me know if this isn't clear enough - in that case I would make it more detailed 👍

**Comment by russellwheatley** [comment]
@nilsreichardt  It isn't clear to me. I have no idea the name of the project or what setup made this occur.

**Comment by nilsreichardt** [comment]
Hmm, I can't reproduce it in a small project. I'm only able to reproduce it in our [Sharezone](https://github.com/SharezoneApp/sharezone-app/tree/main/app) repository when replacing `dev_Sharezone` with `dev Sharezone` as "Product Name" in Xcode.

<img width="727" alt="image" src="https://github.com/invertase/flutterfire_cli/assets/24459435/21f7c400-a215-49cb-b90a-dffb41d59f05">

Since I can't reproduce it in a fresh app (`flutter create name`), I'm going to close this issue.

**Comment by ebsangam** [comment]
Getting the same problem after adding crahlytics.

**Comment by flavioa44** [comment]
I am facing this issue right now. Can't build my App in dev flavor. Production flavor works fine.

**Comment by flavioa44** [comment]
I don't have a space in the path or the name.

**Comment by SametSahin10** [comment]
> I don't have a space in the path or the name, but i just noticed that the path is messed up because of the prefix name of the App when in debug mode.
> 
> build/ios/Debug-dev-iphoneos/[DEV]/Contents/Resources/DWARF.
> 
> Thanks a lot for the hint!

In what way the path is messed up? What's wrong with the path? @flavioa44
