### ISSUE TITLE
Option to forcefully choose which Firebase project to use?

### ISSUE THREAD

**Issue by bizz84** [invertase/flutterfire_cli#25]
My Flutter project has multiple flavors/environments.

Accordingly, I have created multiple Firebase projects:

- `my-shop-ecommerce-dev`
- `my-shop-ecommerce-stg`
- `my-shop-ecommerce-prod`

To generate the configuration for the staging environment, I use this command:

```
flutterfire config --verbose \          
  --out=lib/firebase_options.stg.dart \
  --ios-bundle-id=com.example.verygoodcore.my-shop-ecommerce-flutter.stg \
  --macos-bundle-id=com.example.verygoodcore.my-shop-ecommerce-flutter.stg \
  --android-app-id=com.example.verygoodcore.my_shop_ecommerce_flutter.stg
```

However, the output prints this and chooses the wrong Firebase project:

```
Found 18 Firebase projects. Selecting project my-shop-ecommerce-dev.
```

The impact of this is that I can only use the CLI with my dev environment.

Can this be fixed?

**Comment by Ehesp** [comment]
Have you tried the -p argument to specify which Firebase project to use?

**Comment by bizz84** [comment]
@Ehesp that works, thank you.

I missed that the help for this was in `flutterfire configure --help`.
