### ISSUE TITLE
request:  Upgrade http dependency to match ^1.0.0

### ISSUE THREAD

**Issue by EArminjon** [invertase/flutterfire_cli#255]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command

My project use http: ^1.0.0
```dart
flutter install
``` 

### Description

flutterfire_cli ^0.3.0-dev.19 requires http ^0.13.5

### Reasoning

Would like to add this package as project dev dependency.

**Comment by russellwheatley** [comment]
If you want to make a PR, I will take a look @EArminjon 🙏

**Comment by EArminjon** [comment]
Super, ty :)
