### ISSUE TITLE
Error "Missing google_app_id. Firebase Analytics disabled." 

### ISSUE THREAD

**Issue by harmeet-rgyan** [invertase/flutterfire_cli#26]
I am getting a "Missing google_app_id. Firebase Analytics disabled." error when I am doing firebase setup with FlutterFire Cli, If I am doing it manually I am not getting this error and I am able to see all analytics events in debug view. Here are the logs:

Launching lib\main.dart on DEVICE in debug mode...
Running Gradle task 'assembleDebug'...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Parameter format not correct -
Note: C:\Users\USER\FlutterSDK\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_analytics-9.0.4\android\src\main\java\io\flutter\plugins\firebase\analytics\FlutterFirebaseAnalyticsPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Debug service listening on ws://
Syncing files to device DEVICE.
I/FirebaseApp(14534): Device unlocked: initializing all Firebase APIs for app [DEFAULT]
E/FA      (14534): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
I/Gralloc4(14534): mapper 4.x is not supported
W/Gralloc3(14534): mapper 3.x is not supported
E/FA      (14534): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI

**Comment by gkiwimagi** [comment]
Thanks for posting the issue.  I'm encountering the same...

**Comment by neiljaywarner** [comment]
Can we please escalate this? analytics is one of the main things one would want firebase for...

**Comment by neiljaywarner** [comment]
@harmeet-rgyan  @ivanwhm @gkiwimagi is this still occurring? overall "vibe" of the docs seem like it's made progress

**Comment by 7AveNooN7** [comment]
The issue is still active for me.

**Comment by russellwheatley** [comment]
@harmeet-rgyan  Are you sure this is still an issue? Have you activated the latest FF CLI using `dart pub global activate flutterfire_cli `?

**Comment by pandora-house** [comment]
Same error

**Comment by russellwheatley** [comment]
I've just ran this against the latest dev release and I didn't see any log so I believe it is fixed. Please run `flutterfire configure` command again with relevant arguments.

**Comment by Bridge-Softwares** [comment]
I'm getting same issue !!

**Comment by andredealmei** [comment]
This problem is not fixed
