### ISSUE TITLE
[bug]:  firebase_options.dart not created after running  flutterfire configure

### ISSUE THREAD

**Issue by AndroidPat** [invertase/flutterfire_cli#275]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

1.0.0

### Firebase Tools version

13.7.1

### Flutter Doctor Output

[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-arm64, locale
    en-GB)
    • Flutter version 3.19.5 on channel stable at
      /Users/<myusername>/Documents/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (2 weeks ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/<myusername>/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/<myusername>/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Users/<myusername>/Applications/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.9+0-17.0.9b1087.7-11185874)

[✓] Connected device (3 available)
    • Developer iPhoneX (mobile) • 756b5b0afb3df61c2bea57002e12d9bb56a966cd •
      ios            • iOS 16.7.7 20H330
    • macOS (desktop)            • macos                                    •
      darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 123.0.6312.107
    ! Error: Browsing on the local area network for Mobiles iPhone 15. Ensure
      the device is unlocked and attached with a cable or associated with the
      same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)
    ! Error: Browsing on the local area network for iPhone (170). Ensure the
      device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Description

1. Run flutterfire configure
2. Select Firebase project
3. Select android and ios
Response:
i Firebase android app com.<mypackagename>.flutter registered.              
i Firebase ios app com.<mypackagename> registered.                         
Exception: -e:13:in `block in <main>': undefined method `path' for nil:NilClass (NoMethodError)
	from -e:11:in `each'
	from -e:11:in `find'
	from -e:11:in `<main>'
	
I've tried reinstalling tools, restarting mac, new projects, and different projects.

The result of this error is that firebase_options.dart is not created preventing me from using Firebase in my Flutter project.

### Steps to reproduce

1. Run flutterfire configure
2. Select Firebase project
3. Select android and ios
Response:
i Firebase android app com.<mypackagename>.flutter registered.              
i Firebase ios app com.<mypackagename> registered.                         
Exception: -e:13:in `block in <main>': undefined method `path' for nil:NilClass (NoMethodError)
	from -e:11:in `each'
	from -e:11:in `find'
	from -e:11:in `<main>'
	
I've tried reinstalling tools, restarting mac, new projects, and different projects.

The result of this error is that firebase_options.dart is not created preventing me from using Firebase in my Flutter project.

### Expected behavior

No errors and firebase_options.dart file created.

**Comment by russellwheatley** [comment]
I've just tested on a new Flutter project. Selected ios and android. You can see it was successful, and created `firebase_options.dart` in the screenshot below:
<img width="808" alt="Screenshot 2024-04-11 at 07 28 11" src="https://github.com/invertase/flutterfire_cli/assets/16018629/51a47060-673e-4eb9-a7bc-4e542b1fca3d">

That exception is coming from using `xcodeproj` ruby package which we use to update your Xcode project. If you could strip out your Flutter project of it's code but keep the file structure intact, you could make a reproducible repo for me to take a look at.

**Comment by AndroidPat** [comment]
Thank you for the quick response. As I'm using private frameworks, it wasn't easy to share even a stripped project, so I tried setting up a new one and it worked fine. Then I migrated the content of the old project to the new one and everything works as expected so this issue can be closed.
