### ISSUE TITLE
[bug]:  Invalid argument(s): Option macos-bundle-id, ios-bundle-id, windows-app-id is mandatory

### ISSUE THREAD

**Issue by NIZE0000** [invertase/flutterfire_cli#279]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

1.0.0

### Firebase Tools version

13.7.2

### Flutter Doctor Output

$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel [user-branch], 3.16.5, on Ubuntu 22.04.3 LTS 5.4.0-163-generic, locale en_US.UTF-8)
    ! Flutter version 3.16.5 on channel [user-branch] at /sdks/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    ✗ pkg-config is required for Linux development.
      It is likely available from your distribution (e.g.: apt install pkg-config), or can be downloaded from https://www.freedesktop.org/wiki/Software/pkg-config/
[!] Android Studio (not installed)
[✓] Connected device (1 available)
[✓] Network resources
! Doctor found issues in 4 categories.

### Description

i Found 2 Firebase projects. Selecting project [MASKED].                   
i Selected platforms: android
FirebaseCommandException: An error occured on the Firebase CLI when attempting to run a command.
COMMAND: firebase configure 
ERROR: Please provide value for ios-bundle-id.

### Steps to reproduce

flutterfire config --token "$FIREBASE_TOKEN" \
          --project=xxx-development \
          --platforms=android \
          --android-package-name=net.xxx.dev \
          --yes

### Expected behavior

this script should not show up a error. By default, it would automatically find it if I not send the argument. but it so weird because I already target platforms for android

**Comment by russellwheatley** [comment]
@NIZE0000 - Are you running CLI on CI?

**Comment by NIZE0000** [comment]
@russellwheatley yes I am

**Comment by russellwheatley** [comment]
You'll be happy to know that I've already merged a PR fixing this issue here: https://github.com/invertase/flutterfire_cli/pull/276 😄 

It'll be out in the next release.

**Comment by shamjam** [comment]
When is the next release scheduled?

**Comment by rahullohono** [comment]
Same issue for me as well, CI fails asking for mac os id or web id for the following command.

`flutterfire config --yes --project=<ID> --platforms=android,ios --out=lib/firebase_options.dart --ios-bundle-id=<B_ID> --android-package-name=<P_ID>`

Error:
`Please provide value for web-app-id.`

**Comment by NIZE0000** [comment]
when it will patch ??? I wait for too long or does it have other solution to install fluterfir_cli with specific version?

**Comment by mklarsen** [comment]
What was the solution on this, i still have this issues

**Comment by rahullohono** [comment]
For those looking for a solution on this while the latest update is out, you can use the following:

`dart pub global activate flutterfire_cli 0.2.7` or `dart pub global activate flutterfire_cli 1.0.1-dev.0`

**Comment by russellwheatley** [comment]
@mklarsen - I would use this version:
```
dart pub global activate flutterfire_cli 1.0.1-dev.0
```

**Comment by mklarsen** [comment]
Since i prefered _non_ dev i toke v0.2.7 :-)

So my solution was **dart pub global activate flutterfire_cli 0.2.7**

 thx, to all.

**Comment by NIZE0000** [comment]
thx u all for the solution my pipeline is working now 😊

**Comment by shamjam** [comment]
> @mklarsen - I would use this version:
> 
> ```
> dart pub global activate flutterfire_cli 1.0.1-dev.0
> ```

It doesn't seem to be working for me with this version.

However it does work for:
```
dart pub global activate flutterfire_cli 0.2.7
```
