### ISSUE TITLE
[bug]:  `flutterfire configure` fails in CI for web only project

### ISSUE THREAD

**Issue by OutdatedGuy** [invertase/flutterfire_cli#285]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

1.0.0

### Firebase Tools version

13.7.2

### Flutter Doctor Output

Flutter installed in CI using `subosito/flutter-action@v2`

### Description

flutterfire configure -p {{project_name}} --platforms web -w {{web_app_id}};

### Steps to reproduce

<details><summary>Workflow file</summary>
<p>

```
name: Deploy to Firebase Hosting on PR

on: pull_request

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install Flutter dependencies
        run: flutter pub get;

      - name: Install FlutterFire CLI
        run: dart pub global activate flutterfire_cli;

      - name: Add Dart to PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Install Firebase CLI
        run: npm install -g firebase-tools;

      - name: Set Firebase Project
        run: firebase use preview;
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Configure FlutterFire
        run: flutterfire configure -p ${{ secrets.FIREBASE_PREVIEW_PROJECT }} --platforms web -w ${{ secrets.FIREBASE_DEVELOPMENT_WEB_APP_ID }};
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Enable Firebase Experiments
        run: firebase experiments:enable webframeworks

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: ${{ secrets.FIREBASE_PREVIEW_PROJECT }}
          target: ${{ secrets.FIREBASE_TARGET }}
``` 

</p>
</details>

1. Create a sample/default flutter web project
2. Add above workflow file in `.github/workflows/preview.yml`
3. Push to github as initial commit
4. Add some trivial changes in a different branch and push a PR on github
5. See crash

### Expected behavior

The command to only configure for web and not ask for `android-package-name`

### Additional context and comments

This only occurs in CI not on my local machine.

<details><summary>Error Logs</summary>
<p>

```
25hi Selected platforms: web
FirebaseCommandException: An error occured on the Firebase CLI when attempting to run a command.
COMMAND: firebase configure 
ERROR: Please provide value for android-package-name.
Error: Process completed with exit code 1.
``` 

</p>
</details>

**Comment by daviidmart** [comment]
Same here but with windows only

![image](https://github.com/invertase/flutterfire_cli/assets/10666050/5110d6d0-4cdc-47af-b493-94a079407822)

**Comment by rahullohono** [comment]
Same issue for me as well, CI fails asking for mac os id or web id for the following command. I am only using ios and android

flutterfire config --yes --project=<ID> --platforms=android,ios --out=lib/firebase_options.dart --ios-bundle-id=<B_ID> --android-package-name=<P_ID>

Error:
Please provide value for web-app-id.

This seems to be closed in the following [https://github.com/invertase/flutterfire_cli/issues/279](url) but i am still facing this. Is there a different way to run this?

**Comment by russellwheatley** [comment]
Closing out as
