### ISSUE TITLE
[bug]:  TimeoutException after 0:00:15.000000: Future not completed

### ISSUE THREAD

**Issue by gaganjitgrewal** [invertase/flutterfire_cli#286]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

1.0.0

### Firebase Tools version

13.7.2

### Flutter Doctor Output

[√] Flutter (Channel stable, 3.19.5, on Microsoft Windows [Version 10.0.22631.3447], locale en-IN)
    • Flutter version 3.19.5 on channel stable at D:\Flutter_SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (3 weeks ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\Grewal_Data\Gagan\Android_SDK
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.4)
    • Visual Studio at D:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34714.143
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3447]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 123.0.6312.107
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 123.0.2420.97

[√] Network resources
    • All expected network resources are available.

• No issues found!

### Description

flutterfire configure
⠴ Fetching available Firebase projects...
TimeoutException after 0:00:15.000000: Future not completed

### Steps to reproduce

type - flutterfire configure command

### Expected behavior

Should show the list of projects on the flutter server

### Screenshots

![Screenshot 2024-04-17 105733](https://github.com/invertase/flutterfire_cli/assets/11794286/15b93c65-818d-46b2-a653-773f23764934)

**Comment by russellwheatley** [comment]
@gaganjitgrewal - we've just merged an update to the timeout for getting Firebase projects: https://github.com/invertase/flutterfire_cli/pull/256

It'll be out in the next release 🙏

**Comment by Ravendranmanogar** [comment]
I'm also facing same issue , @gaganjitgrewal  you resolved this issue , help me
