### ISSUE TITLE
flutterfire config isn't working, TimeOutException [bug]:  

### ISSUE THREAD

**Issue by tinygusie2** [invertase/flutterfire_cli#291]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

1.0.0

### Firebase Tools version

13.7.5

### Flutter Doctor Output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.6, on Microsoft Windows [Version 10.0.22635.3350], locale nl-NL)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.74.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

### Description

The cli shows this error when i put in this command 'flutterfire configure', TimeoutException after 0:00:15.000000: Future not completed

### Steps to reproduce

i do not know

### Expected behavior

it should be showing my firebase projects

**Comment by russellwheatley** [comment]
@tinygusie2 - have you tried the latest dev version? We increased the timeout:

```bash
dart pub global activate flutterfire_cli 1.0.1-dev.0 --overwrite
```

Closing out as this should fix the issue, I'll reopen if that isn't the case.
