### ISSUE TITLE
[bug]:  Option macos-bundle-id, ios-bundle-id, windows-app-id is mandatory 

### ISSUE THREAD

**Issue by mklarsen** [invertase/flutterfire_cli#294]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

1.0.0

### Firebase Tools version

13.0.2

### Flutter Doctor Output

[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64 (Rosetta), locale en-US)
    • Flutter version 3.19.6 on channel stable at /Users/runner/hostedtoolcache/flutter/stable-3.19.6-x64
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (4 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/runner/Library/Android/sdk
    • Platform android-34-ext8, build-tools 34.0.0
    • ANDROID_HOME = /Users/runner/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/runner/Library/Android/sdk
    • Java binary at: /Users/runner/hostedtoolcache/Java_Zulu_jdk/17.0.11-9/arm64/bin/java
    • Java version OpenJDK Runtime Environment Zulu17.50+19-CA (build 17.0.11+9-LTS)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode_15.0.1.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.15.2
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64 (Rosetta)
    • Chrome (web)    • chrome • web-javascript • Google Chrome 124.0.6367.62
[✓] Network resources
    • All expected network resources are available.
! Doctor found issues in 2 categories.
25l⠋ Fetching available Firebase projects...   

### Description

From my Github pipeline (has worked until 2 month ago)
 Found 1 Firebase projects. Selecting project SOMEPROJECTID.         
25hi Selected platforms: android
FirebaseCommandException: An error occured on the Firebase CLI when attempting to run a command.
COMMAND: firebase configure 
ERROR: Please provide value for ios-bundle-id.

### Steps to reproduce

firebase apps:list --json --project=PROJECTID
          dart pub global activate flutterfire_cli
          flutter doctor -v          
          flutterfire configure \
            --project=PROJECTID \
            --android-package-name=com.some.name \
            --platforms=android \
            --overwrite-firebase-options \
            --yes

### Expected behavior

automated setup project for uses firebases.option for ANDROID only

### Screenshots

![SD_MKL 2024-05-13 kl  13 45 41](https://github.com/invertase/flutterfire_cli/assets/26963547/da269658-e823-4747-b049-9974a1d9b833)

**Comment by russellwheatley** [comment]
This has been fixed, but it is in the latest dev version. To install, run:
```
dart pub global activate flutterfire_cli 1.0.1-dev.0 --overwrite
```
