### ISSUE TITLE
[bug]:  flutterfire -v command shows incorrect version number

### ISSUE THREAD

**Issue by AhmedLSayed9** [invertase/flutterfire_cli#299]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

1.0.1-dev.0

### Firebase Tools version

13.8.1

### Flutter Doctor Output

[✓] Flutter (Channel stable, 3.19.6, on macOS 14.5 23F79 darwin-arm64, locale en-EG)
    • Flutter version 3.19.6 on channel stable at /Users/bx777/.puro/envs/stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (5 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/bx777/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (4 available)
    • Ahmed’s iPhone (mobile)    • 00008020-00155D412243002E            • ios            • iOS 17.4.1 21E236
    • iPhone 15 Pro Max (mobile) • 1B9F51D0-2C93-4450-B83A-EEC3AF400616 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 124.0.6367.209

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Description

The flutterfire -v command displays the wrong CLI version for version `1.0.1-dev.0`.

### Steps to reproduce

1. Download flutterfire_cli version 1.0.1-dev.0
```
dart pub global activate flutterfire_cli 1.0.1-dev.0 --overwrite
```
2. Run the version command
```
flutterfire -v
```
3. The result shows `1.0.0` instead of `1.0.1-dev.0`

### Expected behavior

When running flutterfire -v I expect the correct CLI version to be displayed.

**Comment by russellwheatley** [comment]
Hi, @AhmedLSayed9, this was missed in the `1.0.1-dev.0` release, but it was updated in the `1.0.1-dev.1` release. I've also updated the release process on the README to capture this update for each release: https://github.com/invertase/flutterfire_cli/pull/302
