### ISSUE TITLE
request:  flutterfire config option to select destination for 'firebase_app_id_file.json' generated file in ios folder

### ISSUE THREAD

**Issue by DamienMrtl** [invertase/flutterfire_cli#304]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command

flutterfire config

### Description

When using flavors with flutter ios, I have two firebase  project dev and prod. I need to select a destination folder for this generated file 'firebase_app_id_file.json' so I can generate one file for each of my flavors.

### Reasoning

It can cause problems because the default file is generated in ios/ folder and if I run my flutterfire configure dev command it can replace the prod infos when rewriting the file.

**Comment by DamienMrtl** [comment]
Thank you I added these parameters for dev and prod flavors

**Comment by russellwheatley** [comment]
`firebase.json` is generated in the root, but the app_id.json files are hidden in the `.dart_tool/flutterfire/` directory 👍
