### ISSUE TITLE
[bug]:  can not install flutterfire

### ISSUE THREAD

**Issue by ByAkm** [invertase/flutterfire_cli#309]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

-

### Firebase Tools version

13.10.2

### Flutter Doctor Output

[✓] Flutter (Channel stable, 3.22.1, on macOS 14.1.2 23B92 darwin-arm64, locale
    en-TM)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.82.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

### Description

Because pub global activate depends on flutterflire any which doesn't exist
  (could not find package flutterflire at https://pub.dev), version solving
  failed.

### Steps to reproduce

-

### Expected behavior

-

### Screenshots

-

### Additional context and comments

-

**Comment by ByAkm** [comment]
please help

**Comment by qwadrox** [comment]
Flutterflire is a typo. Use `dart pub global activate flutterfire_cli` from https://pub.dev/packages/flutterfire_cli

(Copy and paste it to your terminal)

**Comment by qwadrox** [comment]
> please help

Flutterflire is a typo. Use `dart pub global activate flutterfire_cli` from https://pub.dev/packages/flutterfire_cli

(Copy and paste it to your terminal)

**Comment by russellwheatley** [comment]
@ByAkm - Try:
```
dart pub global activate flutterfire_cli 1.0.1-dev.1
```

which will install the latest dev version with latest fixes 👍
