### ISSUE TITLE
How we can be able to configure FlutterFire CLI for SHA1?

### ISSUE THREAD

**Issue by QasimRailo** [invertase/flutterfire_cli#31]
I am trying to add a SHA1 certificate to a new Firebase Project

In the [FlutterFire](https://firebase.flutter.dev/docs/manual-installation) Overview there is a statement that the manual configuration should get avoided. Instead we should use the flutterfire configure command line with the CLI.

There is no clarification on how to add the SHA1 certificate with the CLI.

Is this even possible? If not should I then do the whole configuration manually?

**Comment by Kiruel** [comment]
I would like to know too, I use push notification in release mode and I can not received it. And I suppose it's because my SHA1 is not on the flutterfire config file.

**Comment by Kiruel** [comment]
Ok it was a problem with Dart method static, nothing related to SHA1.

**Comment by russellwheatley** [comment]
SHA-1 key needs to be manually added to the Firebase console, this isn't likely to change anytime soon. As far as I'm aware, I don't think it is possible to even push the SHA-1 key via the Firebase CLI which is the underlying tool for the FlutterFire CLI.
