### ISSUE TITLE
[bug]:  Custom shell scripts in build phases do nothing 

### ISSUE THREAD

**Issue by qwadrox** [invertase/flutterfire_cli#310]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

1.0.0

### Firebase Tools version

13.10.2

### Flutter Doctor Output

[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale
    en-HU)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.3)
[✓] VS Code (version 1.90.0)
[✓] Connected device (6 available)
    ! Error: Browsing on the local area network for -- iPhone. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!

### Description

The CLI-injected shell script execute without errors, but it fails to produce the expected results. Specifically, the script that should copy the GoogleService-Info file to the build directory does not copy the file. 
Additionally, the script intended to upload Crashlytics debug symbols does not upload them, and exit with error below: 

```bash
2024-06-06 08:39:42.688 upload-symbols[24420:159782] Unable to get file attributes for dSYM file at path "/Users/mateboros/Documents/Github/my_catalog_app/build/ios/Release-dev-iphoneos/Catalog/Contents/Resources/DWARF"

    #0      UploadCrashlyticsSymbols.run (package:flutterfire_cli/src/commands/upload_symbols.dart:406:7)
    <asynchronous suspension>
    #1      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
    <asynchronous suspension>
    #2      main (file:///Users/mateboros/.pub-cache/hosted/pub.dev/flutterfire_cli-1.0.0/bin/flutterfire.dart:63:5)
    <asynchronous suspension>
```

### Steps to reproduce

SAMPLE: https://github.com/qwadrox/my_catalog_app

1. Create a new flutter app 
2. Setup Flavors on iOS based on: https://docs.flutter.dev/deployment/flavors
3. Run the cli with build configuration option for iOS. Choose let's say: Debug-dev
4. Start the application and you will see the error: Unable to get file attributes for dSYM file.
Also, I couldn't find anywhere of the output directories the GoogleService-Info.json.

### Expected behavior

Running the cli should correctly setup the shell scripts. All path should match the actual path. dSYM should be uploaded build time.  GoogleService-Info.json should be located in the products build directory. 

### Workaround

https://github.com/firebase/flutterfire/issues/11547#issuecomment-1707347602

**Comment by russellwheatley** [comment]
The path seems incorrect for DSYM: `2024-06-06 08:39:42.688 upload-symbols[24420:159782] Unable to get file attributes for dSYM file at path "/Users/mateboros/Documents/Github/my_catalog_app/build/ios/Release-dev-iphoneos/Catalog/Contents/Resources/DWARF"`

Take a look at my path for example:
`/Users/russellwheatley/Library/Developer/Xcode/DerivedData/Runner-cqtrobmgajrkdoekebvuxzxiddfo/Build/Products/Release-iphoneos/Runner.app.dSYM`

I would actually have a look in your build folder for the location of debug symbols because something is misconfigured. Here is how we get Xcode DSYM: https://github.com/invertase/flutterfire_cli/blob/main/packages/flutterfire_cli/lib/src/commands/upload_symbols.dart#L376-L377

If you want to see the value of these variable, run these commands:
```bash
cd ios/
xcodebuild -showBuildSettings
```

This should print out the Xcode build arguments. Take a look at the values for `DWARF_DSYM_FOLDER_PATH` and `DWARF_DSYM_FILE_NAME` for the full path

**Comment by qwadrox** [comment]
The output is this:

```
    DWARF_DSYM_FILE_NAME = Catalog.app.dSYM
    DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT = NO
    DWARF_DSYM_FOLDER_PATH = /Users/mateboros/Library/Developer/Xcode/DerivedData/Runner-ahnzublnbgpgfphjcjgkpmxelgzr/Build/Products/Release-prod-iphoneos
```


but still getting: 

```
    2024-07-03 21:40:12.055 upload-symbols[8275:80694] Unable to get file attributes for dSYM file at path "/Users/mateboros/Documents/Github/my_catalog_app/build/ios/Debug-dev-iphonesimulator/Catalog/Contents/Resources/DWARF"
```

Please check the repro sample, and the referenced workaround that eventually solved the problem.

**Comment by russellwheatley** [comment]
I'd advise against the workaround, it will be overwritten when you run flutterfire configure. 

I cloned your project, ran the same commands for configuring but with my own firebase project.

I then ran the following:
```bash
flutter run --flavor=prod --verbose > output.log 2>&1
```

Here is the log for successfully uploading debug symbols:
```bash
           Running upload-symbols in Build Phase mode
           Validating build environment for Crashlytics...
           Processing dSYMs...
           Successfully submitted symbols for architecture arm64 with UUID 034f61fa1f7537e1953152e7d6fb5266 in dSYM: /Users/russellwheatley/projects/devTests/my_catalog_app/build/ios/Debug-prod-iphonesimulator/Catalog.app.dSYM
           [32mSuccessfully uploaded Crashlytics build event and symbols[0m
           Running upload-symbols in Build Phase mode
           Validating build environment for Crashlytics...
           Processing dSYMs...
           Successfully submitted symbols for architecture arm64 with UUID 034f61fa1f7537e1953152e7d6fb5266 in dSYM: /Users/russellwheatley/projects/devTests/my_catalog_app/build/ios/Debug-prod-iphonesimulator/Catalog.app.dSYM
           [32mSuccessfully uploaded Crashlytics build event and symbols[0m
```

Closing as this is a user configuration issue.

**Comment by qwadrox** [comment]
"user configuration issue" What do you mean by that? could you point out what is misconfigure? 
In the repro steps I mentioned, I used the dev flavor. 

So I tried again running: 

```
flutter run --flavor=dev --verbose > output.log 2>&1
```

In the output file the error still: 

```sh
Unable to get file attributes for dSYM file at path "/Users/mateboros/Documents/Github/my_catalog_app/build/ios/Debug-dev-iphonesimulator/Catalog/Contents/Resources/DWARF"
```

but i also see this: 

```sh

PhaseScriptExecution FlutterFire:\ \"flutterfire\ upload-crashlytics-symbols\" /Users/mateboros/Library/Developer/Xcode/DerivedData/Runner-ajmxjwmlxxrtseafejmdyldfqixn/Build/Intermediates.noindex/Runner.build/Debug-dev-iphonesimulator/Runner.build/Script-40627E6C380B162DBFB56451.sh (in target 'Runner' from project 'Runner')
****
export DWARF_DSYM_FILE_NAME\=Catalog\ dev.app.dSYM
export DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT\=NO
export DWARF_DSYM_FOLDER_PATH\=/Users/mateboros/Documents/Github/my_catalog_app/build/ios/Debug-dev-iphonesimulator
```

which is different than the output of `xcodebuild -showBuildSettings` For me this command outputs just what i said. 

So I decided to rename ProductName from Xcode: 
```diff
ios/Runner.xcodeproj/project.pbxproj
-PRODUCT_NAME = "Catalog dev";
+PRODUCT_NAME = Catalogdev;
```

And now it works. Successfully uploaded Crashlytics build event and symbols.
@russellwheatley I think the problem is on your side. The path handled incorrectly or something because renaming the app should not effect the upload. 
Furthermore it seems the recommended xcodebuild command does not outputs the path used by the build phase.

**Comment by qwadrox** [comment]
@russellwheatley
