### ISSUE TITLE
[bug]:  Upload Crashlytics Symbols dSYM Files NOT working!

### ISSUE THREAD

**Issue by Shatha-Naami** [invertase/flutterfire_cli#314]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

1.0.0

### Firebase Tools version

13.11.2

### Flutter Doctor Output

<img width="813" alt="image" src="https://github.com/invertase/flutterfire_cli/assets/60509531/590ddcf6-05ac-4f80-a252-c43b53c9123e">

### Description

I followed the [Firebase Crashlytics setup guide for Flutter](https://firebase.google.com/docs/crashlytics/get-started?hl=en&platform=flutter) to integrate Firebase Crashlytics into my Flutter app. While I am able to see crash reports and user metrics in the Firebase Analytics dashboard, the dSYM files are not being uploaded automatically.

### Steps to reproduce

1. Follow the official [Firebase Crashlytics setup guide for Flutter](https://firebase.google.com/docs/crashlytics/get-started?hl=en&platform=flutter).
2. Complete all the steps as instructed, including adding the necessary dependencies and setting up the Crashlytics SDK.
3. Run the app and force a crash to test the integration.
4. Check the Firebase Analytics dashboard for crash reports and user metrics.

### Expected behavior

The dSYM files should be uploaded automatically without any manual intervention.

**Actual Behavior:**
Although crash reports and user metrics appear in the Firebase Analytics dashboard, the dSYM files are not uploaded automatically.

### Screenshots

<img width="860" alt="image" src="https://github.com/invertase/flutterfire_cli/assets/60509531/15eefa4e-4810-415d-a37f-a433bbef588b">

![image](https://github.com/invertase/flutterfire_cli/assets/60509531/eed68703-ec7d-4d42-9049-9585903da7c8)

<img width="801" alt="image" src="https://github.com/invertase/flutterfire_cli/assets/60509531/ea2cf10d-3324-4724-ae64-a79c939837a7">

### Additional context and comments

Flutter version: **3.22.2**
Firebase Crashlytics version: **^4.0.1**
Xcode version: **15.4**

**Comment by Shatha-Naami** [comment]
@russellwheatley  any updates?

**Comment by DougSig** [comment]
I am also experiencing this. Have been since May 29th when I first integrated crashlytics -- have not had a successful dsym upload yet despite logs showing the script finishing successfully.

**Comment by DougSig** [comment]
Additionally, `flutterfire configure` does not add the input files that the iOS instructions say are required -- and if you manually add them, running `flutterfire configure` overrides it and removes them. However, manually adding the input files still does not solve the uploading issue.

**Comment by michaelowolf** [comment]
We're getting the same - I've tried spitting out the logs as described in https://github.com/invertase/flutterfire_cli/issues/249 and they suggest the upload is successful:
```
Running upload-symbols in Build Phase mode
Validating build environment for Crashlytics...
Processing dSYMs...
Successfully submitted symbols for architecture x86_64 with UUID 36303faa3e1f34a5ba0279f924182260 in dSYM: /Users/[..]/build/ios/Debug-development-iphonesimulator/Runner.app.dSYM
[32mSuccessfully uploaded Crashlytics build event and symbols[0m
Running upload-symbols in Build Phase mode
Validating build environment for Crashlytics...
Processing dSYMs...
Successfully submitted symbols for architecture x86_64 with UUID 36303faa3e1f34a5ba0279f924182260 in dSYM: /Users/[..]/build/ios/Debug-development-iphonesimulator/Runner.app.dSYM
[32mSuccessfully uploaded Crashlytics build event and symbols[0m
```

But the dSYM(s) never appear in the Firebase console.

If helpful, we're using Very Good CLI, so we have [build flavours for production, staging and development](https://cli.vgv.dev/docs/templates/core#running-the-project-), and a Firebase project per environment. This also means we don't have a permanent top-level `GoogleService-Info.plist`, but rather copy in an environment-specific version at build time. I've not tried to manually configure the input files for the build phase (yet!).

**Comment by Shatha-Naami** [comment]
> We're getting the same - I've tried spitting out the logs as described in #249 and they suggest the upload is successful:
> 
> ```
> Running upload-symbols in Build Phase mode
> Validating build environment for Crashlytics...
> Processing dSYMs...
> Successfully submitted symbols for architecture x86_64 with UUID 36303faa3e1f34a5ba0279f924182260 in dSYM: /Users/[..]/build/ios/Debug-development-iphonesimulator/Runner.app.dSYM
> �[32mSuccessfully uploaded Crashlytics build event and symbols�[0m
> Running upload-symbols in Build Phase mode
> Validating build environment for Crashlytics...
> Processing dSYMs...
> Successfully submitted symbols for architecture x86_64 with UUID 36303faa3e1f34a5ba0279f924182260 in dSYM: /Users/[..]/build/ios/Debug-development-iphonesimulator/Runner.app.dSYM
> �[32mSuccessfully uploaded Crashlytics build event and symbols�[0m
> ```
> 
> But the dSYM(s) never appear in the Firebase console.
> 
> If helpful, we're using Very Good CLI, so we have [build flavours for production, staging and development](https://cli.vgv.dev/docs/templates/core#running-the-project-), and a Firebase project per environment. This also means we don't have a permanent top-level `GoogleService-Info.plist`, but rather copy in an environment-specific version at build time. I've not tried to manually configure the input files for the build phase (yet!).

@michaelowolf  
I tried running the command:
`flutter build ios --obfuscate --split-debug-info=./ios-build`

The console indicated that everything worked fine, and I received the output:

<img width="921" alt="Screenshot 2024-06-20 at 1 20 21 PM" src="https://github.com/invertase/flutterfire_cli/assets/60509531/f58accd2-d89c-45ec-a485-db51e33eedc3">


However, when I checked Firebase Crashlytics, I found that the dSYM(s) were not uploaded.

<img width="999" alt="image" src="https://github.com/invertase/flutterfire_cli/assets/60509531/d496ce67-2fe1-4a4b-a117-50d40bb1b781">

**Comment by Shatha-Naami** [comment]
> Additionally, `flutterfire configure` does not add the input files that the iOS instructions say are required -- and if you manually add them, running `flutterfire configure` overrides it and removes them. However, manually adding the input files still does not solve the uploading issue.

Exactly, @DougSig .
That's what I tried to do. I added all the steps manually and attempted to upload the dSYM files, but they still didn't upload! :(

**Comment by russellwheatley** [comment]
Hey @Shatha-Naami - as mentioned [here](https://github.com/invertase/flutterfire_cli/issues/315#issuecomment-2188381641), please check to see if that file is missing. Could other folks experiencing this issue also let me know if that file is missing. Thanks 🙏

**Comment by michaelowolf** [comment]
> Hey @Shatha-Naami - as mentioned [here](https://github.com/invertase/flutterfire_cli/issues/315#issuecomment-2188381641), please check to see if that file is missing. Could other folks experiencing this issue also let me know if that file is missing. Thanks 🙏

Hey @russellwheatley, I have a version of `app_id_file.json` at `.dart_tool/flutterfire/platforms/ios/targets/Runner/{Firebase project id}/app_id_file.json` for my development Firebase project (of which the contents look correct), but no equivalent for my production Firebase project (although IIRC, neither development nor production were uploading the dSYMs).

**Comment by Shatha-Naami** [comment]
> Hey @Shatha-Naami - as mentioned [here](https://github.com/invertase/flutterfire_cli/issues/315#issuecomment-2188381641), please check to see if that file is missing. Could other folks experiencing this issue also let me know if that file is missing. Thanks 🙏

Hey @russellwheatley,
When I checked my app, unfortunately, **I didn't find the file**. 
I'm sure I followed all the steps in the documentation, so how can I generate the file?

<img width="389" alt="image" src="https://github.com/invertase/flutterfire_cli/assets/60509531/fdb13a25-4ebf-44f7-a02b-5c6fdd9e1f8c">

**Comment by russellwheatley** [comment]
@Shatha-Naami - what version of FlutterFire CLI are you using? The script is added to your build phases and it generates the file when you build you app (or uses existing file if you have built app previously). It is then used to upload symbols.

**Comment by russellwheatley** [comment]
@michaelowolf - you said you were using VGV CLI? They set their apps up to use build configuration. You should probably be configuring your app to use build configuration instead of target. In other words, use this flag - `--ios-build-config=` instead of `--ios-target=`. Unless you have some custom setup of course which doesn't make use of build configuration.

**Comment by Shatha-Naami** [comment]
> @Shatha-Naami - what version of FlutterFire CLI are you using? The script is added to your build phases and it generates the file when you build you app (or uses existing file if you have built app previously). It is then used to upload symbols.

@russellwheatley 
The version  of FlutterFire CLI is --> **1.0.0** 

After following [this document](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=ios) and checking Xcode's Build Phases, I found that this run script was generated automatically and not created manually.
I didn't use any previously built files.

<img width="834" alt="image" src="https://github.com/invertase/flutterfire_cli/assets/60509531/c73fc723-a195-4bba-b4bd-f2780eeb0e1a">

**Comment by tpkowastaken** [comment]
Hi, I have been experiencing the same issue and that's just after freshly installing everything - new mac, new flutter, new xcode, new project. It's very easily reproducable, please look into it. Thank you for your time and effort.

The issue in question: https://github.com/firebase/flutterfire/issues/12990

**Comment by tpkowastaken** [comment]
There is a duplicate of this already:
1. https://github.com/invertase/flutterfire_cli/issues/321

**Comment by Shatha-Naami** [comment]
@tpkowastaken 
Thanks for your support!.

I follow your steps, and this is the final result:

<img width="836" alt="image" src="https://github.com/invertase/flutterfire_cli/assets/60509531/fae02244-a57d-4a75-b692-63fc0041a358">

<img width="412" alt="image" src="https://github.com/invertase/flutterfire_cli/assets/60509531/841e9f89-6f88-4bd0-8561-1c2e31850734">

and I'm already update values on` firebase_app_id_file.json`
once moving to crashlytics tab in firebase, still show to me 
**This app has 352 unprocessed crashes. Upload 17 dSYM files to process them.**

So what I miss in the steps?

**Comment by tpkowastaken** [comment]
@Shatha-Naami 
I'm terribly sorry the solution doesn't work. I tried to use an older system that was supplied by an older flutterfire cli version hovewer since i checked the `For install builds only` option it only runs when building an ipa file. I tested it only by building xcarchive which didn't upload the symbols. I'm going to debug it further and hopefully bring results. Thank you for your patience.

**Comment by RaphaelJenni** [comment]
I encountered the same issue. After investigating the source code:(https://github.com/invertase/flutterfire_cli/blob/016699f2836659c3fe948635bba573ceff73117b/packages/flutterfire_cli/lib/src/commands/upload_symbols.dart#L276

I noticed that there are three options `buildConfiguration`, `target`, `defaultConfig`. By default flutterfire currently uses `defaultConfig` and also sets up the project like that. More specific, the command flag added to the xcodeproj uses the defaultConfig which in turn uses the default configuration in the firebase.json file.

In order to make multi flavor setups working you need to change the firebase.json to uses `targets` instead of `default`:
```json
{
  "flutter": {
    "platforms": {
      "ios": {
        "default": {
          "projectId": "your-project-id",
          "appId": "1:1:ios:1",
          "uploadDebugSymbols": false,
          "fileOutput": "ios/Runner/GoogleService-Info.plist"
        }
      },
      "dart": {
        "lib/firebase_options.dart": {
          "projectId": "your-project-id",
          "configurations": {
            "ios": "1:1:ios:1"
          }
        }
      }
    }
  }
}

```

to 

```json
{
  "flutter": {
    "platforms": {
      "ios": {
        "targets": {
          "develop": {
            "projectId": "your-project-id-develop",
            "appId": "1:1:ios:1",
            "uploadDebugSymbols": true,
            "fileOutput": "ios/Runner/GoogleService-Info.plist"
          },
          "production": {
            "projectId": "your-project-id",
            "appId": "1:1:ios:1",
            "uploadDebugSymbols": true,
            "fileOutput": "ios/Runner/GoogleService-Info.plist"
          }
        }
      },
      "dart": {
        "lib/firebase_options.develop.dart": {
          "projectId": "your-project-id-develop",
          "configurations": {
            "ios": "1:1:ios:1"
          }
        },
        "lib/firebase_options.production.dart": {
          "projectId": "your-project-id",
          "configurations": {
            "ios": "1:1:ios:1"
          }
        }
      }
    }
  }
}
```

Furthermore in the `FlutterFire: "flutterfire upload-crashlytics-symbols"` build phase (in XCode > Runner > Runner (Targets) > Build Phases) replace the ` --default-config=default` with `--target=${FLAVOR}` (`$FLAVOR` being a user defined build setting added by me).

All those changes should result in a `app_id_file.json` located in `.dart_tool/flutterfire/platforms/ios/targets/...` after running the app. (Make sure to run a `flutter clean && flutter pub get` before)
If so, the symbols should be uploaded - if not - check that you don't have any typos (it won't give you an error).

Hope this helps.

**Comment by RaphaelJenni** [comment]
@Shatha-Naami Update the firebase dependencies to the newest version and run `flutterfire configure`. This should generate a new Build Step (you can delete the old one). The new build step doesn't depend on the `firebase_app_id_file.json` anymore. Hope this helps.

**Comment by Shatha-Naami** [comment]
> @Shatha-Naami Update the firebase dependencies to the newest version and run `flutterfire configure`. This should generate a new Build Step (you can delete the old one). The new build step doesn't depend on the `firebase_app_id_file.json` anymore. Hope this helps.

@RaphaelJenni
I upgraded the Firebase dependencies to the latest versions and ran `flutterfire configure`. 
After deleting all old files, I checked Crashlytics on Firebase. A crash was reported!

<img width="360" alt="image" src="https://github.com/invertase/flutterfire_cli/assets/60509531/f65dd144-2046-4e0e-87cd-62ade2b8f633">

Thanks All!

**Comment by DougSig** [comment]
@Shatha-Naami great to hear! Which files did you delete? I updated just like you and am getting the following error:

<img width="1356" alt="Screenshot 2024-07-02 at 1 44 11 PM" src="https://github.com/invertase/flutterfire_cli/assets/5641478/f05397b3-9cae-4a2a-a3c2-7d10e3ec336d">

**Comment by DevHusariaSolutions** [comment]
> @Shatha-Naami I'm terribly sorry the solution doesn't work. I tried to use an older system that was supplied by an older flutterfire cli version hovewer since i checked the `For install builds only` option it only runs when building an ipa file. I tested it only by building xcarchive which didn't upload the symbols. I'm going to debug it further and hopefully bring results. Thank you for your patience.

Confirmed that this helped, without need to change any Firebase package version or even cleaning project again.

**Comment by michaelowolf** [comment]
> uild-config

@russellwheatley sorry to necro this - just wanted to mention that (having finally had time to come back to this) your suggestion worked. Thanks for the help with that, I'd missed completely the multi-build configuration set up section in the README.

Probably not the right place to mention this (and I may be missing more docs elsewhere!), but since https://firebase.flutter.dev/docs/overview/ is marked out of date and points to https://firebase.google.com/docs/flutter/setup, it would be really good to get some of the Flutterfire CLI readme included in or linked to from those Firebase docs.

**Comment by hadi7khan** [comment]
@RaphaelJenni I am using flavors in my project and I tried to use your e

> I encountered the same issue. After investigating the source code:(
> 
> https://github.com/invertase/flutterfire_cli/blob/016699f2836659c3fe948635bba573ceff73117b/packages/flutterfire_cli/lib/src/commands/upload_symbols.dart#L276
> 
> I noticed that there are three options `buildConfiguration`, `target`, `defaultConfig`. By default flutterfire currently uses `defaultConfig` and also sets up the project like that. More specific, the command flag added to the xcodeproj uses the defaultConfig which in turn uses the default configuration in the firebase.json file.
> 
> In order to make multi flavor setups working you need to change the firebase.json to uses `targets` instead of `default`:
> 
> ```json
> {
>   "flutter": {
>     "platforms": {
>       "ios": {
>         "default": {
>           "projectId": "your-project-id",
>           "appId": "1:1:ios:1",
>           "uploadDebugSymbols": false,
>           "fileOutput": "ios/Runner/GoogleService-Info.plist"
>         }
>       },
>       "dart": {
>         "lib/firebase_options.dart": {
>           "projectId": "your-project-id",
>           "configurations": {
>             "ios": "1:1:ios:1"
>           }
>         }
>       }
>     }
>   }
> }
> ```
> 
> to
> 
> ```json
> {
>   "flutter": {
>     "platforms": {
>       "ios": {
>         "targets": {
>           "develop": {
>             "projectId": "your-project-id-develop",
>             "appId": "1:1:ios:1",
>             "uploadDebugSymbols": true,
>             "fileOutput": "ios/Runner/GoogleService-Info.plist"
>           },
>           "production": {
>             "projectId": "your-project-id",
>             "appId": "1:1:ios:1",
>             "uploadDebugSymbols": true,
>             "fileOutput": "ios/Runner/GoogleService-Info.plist"
>           }
>         }
>       },
>       "dart": {
>         "lib/firebase_options.develop.dart": {
>           "projectId": "your-project-id-develop",
>           "configurations": {
>             "ios": "1:1:ios:1"
>           }
>         },
>         "lib/firebase_options.production.dart": {
>           "projectId": "your-project-id",
>           "configurations": {
>             "ios": "1:1:ios:1"
>           }
>         }
>       }
>     }
>   }
> }
> ```
> 
> Furthermore in the `FlutterFire: "flutterfire upload-crashlytics-symbols"` build phase (in XCode > Runner > Runner (Targets) > Build Phases) replace the ` --default-config=default` with `--target=${FLAVOR}` (`$FLAVOR` being a user defined build setting added by me).
> 
> All those changes should result in a `app_id_file.json` located in `.dart_tool/flutterfire/platforms/ios/targets/...` after running the app. (Make sure to run a `flutter clean && flutter pub get` before) If so, the symbols should be uploaded - if not - check that you don't have any typos (it won't give you an error).
> 
> Hope this helps.

I tried to use your way because I am also using flavors. After doing the changes I am unable to run my project. Throws error: `Could not build the precompiled application for the device.
Error (Xcode): 'Flutter/Flutter.h' file not found`

Can you please share the User defined flavor setup screenshot? and FlutterFire script needs to run at last in build phase? 
This is my Script: `
#!/bin/bash
PATH="${PATH}:$FLUTTER_ROOT/bin:$HOME/.pub-cache/bin"
flutterfire upload-crashlytics-symbols --upload-symbols-script-path="$PODS_ROOT/FirebaseCrashlytics/upload-symbols" --platform=ios --apple-project-path="${SRCROOT}" --env-platform-name="${PLATFORM_NAME}" --env-configuration="${CONFIGURATION}" --env-project-dir="${PROJECT_DIR}" --env-built-products-dir="${BUILT_PRODUCTS_DIR}" --env-dwarf-dsym-folder-path="${DWARF_DSYM_FOLDER_PATH}" --env-dwarf-dsym-file-name="${DWARF_DSYM_FILE_NAME}" --env-infoplist-path="${INFOPLIST_PATH}" --target=${FLAVOR}
` 
My user defined Flavor setup: 
<img width="486" alt="Screenshot 2024-10-31 at 1 50 43 PM" src="https://github.com/user-attachments/assets/6194445b-8fa0-4562-825d-ea2cb0f9ce9c">
