### ISSUE TITLE
[bug]:  `firebase_app_id_file.json` does not exist for `upload-symbols` script

### ISSUE THREAD

**Issue by OutdatedGuy** [invertase/flutterfire_cli#315]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

1.0.0

### Firebase Tools version

13.11.2

### Flutter Doctor Output

```bash
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-IN)
    • Flutter version 3.22.2 on channel stable at /Users/user/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (11 days ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.90.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] VS Code (version 1.91.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)            
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 126.0.6478.62

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Description

Running `flutterfire configure` does not create the `firebase_app_id_file.json` file anymore and instead creates `firebase.json`. Hence when running `pod update` or `pod install` below warning is printed:

```bash
Warning: firebase_app_id_file.json file does not exist. This may cause issues in upload-symbols. If this error is unexpected, try running flutterfire configure again.
```

### Steps to reproduce

1. Run `flutterfire configure`
2. Run `pod install`
3. See warning

### Expected behavior

Either `flutterfire configure` should create a `firebase_app_id_file.json` file or the `upload-symbols` script shouldn't rely on `firebase_app_id_file.json` and maybe on `firebase.json` if necessary.

**Comment by patterueldev** [comment]
Encountering this as well. When I run pod install, I see the warning.
<img width="1356" alt="Screenshot 2024-06-19 at 2 36 09 PM" src="https://github.com/invertase/flutterfire_cli/assets/39513487/03dd3133-0fd2-4e6c-9dc2-1b1fcde18f88">

Prior to this, I never noticed this. And I was wondering why I keep receiving emails from Firebase about missing dSYM. Hopefully this gets fixed.

**Comment by Shatha-Naami** [comment]
> flutterfire configure

I have the same warning and the same issue with uploading dSYM files to Crashlytics.
https://github.com/invertase/flutterfire_cli/issues/314

**Comment by russellwheatley** [comment]
Hey, could you let me know what you see on this path in your project?

`.dart_tool/flutterfire/platforms/ios/default/flutterfire-cli-test-f6f57/app_id_file.json`

 For my project, I used default config and I used my Firebase project `flutterfire-cli-test-f6f57` which is why I have the directories `default/flutterfire-cli-test-f6f57/`, yours will also match the setup you're using.


To give some context, when you run your app, it will add the relevant `app_id_file.json` file which is used to upload symbols [here](https://github.com/invertase/flutterfire_cli/blob/main/packages/flutterfire_cli/lib/src/commands/upload_symbols.dart#L370).


<img width="1451" alt="Screenshot 2024-06-25 at 10 03 18" src="https://github.com/invertase/flutterfire_cli/assets/16018629/415ee4dd-861e-4e86-bce8-8aa73d237c57">

Something must be incorrectly configured for it to be missing.

**Comment by OutdatedGuy** [comment]
> Hey, could you let me know what you see on this path in your project?

Hey @russellwheatley, I can see that this file exists with `GOOGLE_APP_ID` and `FIREBASE_PROJECT_ID` in it.

<hr />

### Additional Information:

- One of my old project which didn't used the latest version (stable public release) of `flutterfire_cli` have the `[firebase_crashlytics] Crashlytics Upload Symbols` script as mentioned in the [official docs](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=flutter#apple-upload-dsym-script-configuration), but the new project doesn't have it.
- Also the [firebase_crashlytics](https://pub.dev/packages/firebase_crashlytics) plugin still relies on the `firebase_app_id_file.json`  file to upload dSYM.

  https://github.com/firebase/flutterfire/blob/70a3fbc97ec34c811616e92333aae299dd2ef569/packages/firebase_crashlytics/firebase_crashlytics/ios/crashlytics_add_upload_symbols#L42-L55

### What I think

Looks like there are two simultaneous issues:

1. `flutterfire_cli` not adding the `[firebase_crashlytics] Crashlytics Upload Symbols` script
2. `firebase_crashlytics` still relying on `firebase_app_id_file.json` instead of the new `app_id_file.json` file

**Comment by russellwheatley** [comment]
> One of my old project which didn't used the latest version (stable public release) of flutterfire_cli have the [firebase_crashlytics] Crashlytics Upload Symbols script as mentioned in the [official docs](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=flutter#apple-upload-dsym-script-configuration), but the new project doesn't have it.

We don't use the script in the Firebase documentation for the latest FlutterFire CLI. We add a script to build phases that calls this method on FlutterFire CLI which uploads debug symbols: https://github.com/invertase/flutterfire_cli/blob/main/packages/flutterfire_cli/lib/src/commands/upload_symbols.dart

> Also the [firebase_crashlytics](https://pub.dev/packages/firebase_crashlytics) plugin still relies on the firebase_app_id_file.json file to upload dSYM.
> [firebase/flutterfire@70a3fbc/packages/firebase_crashlytics/firebase_crashlytics/ios/crashlytics_add_upload_symbols#L42-L55](https://github.com/firebase/flutterfire/blob/70a3fbc97ec34c811616e92333aae299dd2ef569/packages/firebase_crashlytics/firebase_crashlytics/ios/crashlytics_add_upload_symbols#L42-L55)
We kept this method for backwards compatibility, if the old json file doesn't exist, it does nothing. So nothing to worry about.

**Comment by OutdatedGuy** [comment]
> We kept this method for backwards compatibility, if the old json file doesn't exist, it does nothing. So nothing to worry about.

So looks like the warning is from the backwards compatible `firebase_crashlytics`. Then I think this resolves the main point of this issue.

You can go ahead and close this issue.

**Comment by kasimr-oxc** [comment]
I did found the `firebase_app_id.json` but, inside the `plugins` folders.

![image_2024_12_11T04_23_19_783Z](https://github.com/user-attachments/assets/7cbb8cc3-ac0d-435f-9e61-4e8549dfc43d)

**Comment by rxvivek** [comment]
facing same issue
