### ISSUE TITLE
[bug]:   flutterfire configure command error

### ISSUE THREAD

**Issue by dev-kv2001** [invertase/flutterfire_cli#325]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

1.0.0

### Firebase Tools version

13.13.0

### Flutter Doctor Output

[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-IN)
    • Flutter version 3.22.2 on channel stable at /Users/khushal/Development/SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (4 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/khushal/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/khushal/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.91.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554                        • android-arm64  • Android 14 (API 34) (emulator)
    • iPhone Xs (mobile)              • 436C8C3D-804D-433E-A4BB-2977D97541D4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 126.0.6478.127

[✓] Network resources
    • All expected network resources are available.

### Description

when i run this command flutterfire configure --project=myproject-id

### Steps to reproduce

open terminal 
hit this command 
flutterfire configure --project=myproject-id

✔ Which platforms should your configuration support (use arrow keys & space to select)? · android, ios                                                                                                                                  
✔ Which Android application id (or package name) do you want to use for this configuration, e.g. 'com.example.app'? · com.my.app                                                                                                
i Firebase android app com.my.app registered.                                                                                                                                                                                   
i Firebase ios appcom.my.app registered.                                                                                                                                                                                       
Exception: <internal:/opt/homebrew/Cellar/ruby/3.3.3/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- xcodeproj (LoadError)
        from <internal:/opt/homebrew/Cellar/ruby/3.3.3/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from -e:1:in `<main>'

### Expected behavior

it should configure my project with firebase

### Screenshots

![image](https://github.com/invertase/flutterfire_cli/assets/174802039/48933672-6e77-45c9-963b-0cd21459daff)

**Comment by hrithikm2cd** [comment]
@dev-kv2001 I am having the same issue, how did you solve it?

**Comment by dev-kv2001** [comment]
@hrithikm2cd  

try  sudo gem install xcodeproj
