### ISSUE TITLE
[bug]:  TimeoutException after 0:00:15.000000: Future not completed

### ISSUE THREAD

**Issue by Musabumair098** [invertase/flutterfire_cli#337]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

1.0.0

### Firebase Tools version

13.16.0

### Flutter Doctor Output

  • Flutter version 3.22.3 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (7 weeks ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

### Description

it create issue while fetching project from cli :
⠼ Fetching available Firebase projects...
TimeoutException after 0:00:15.000000: Future not completed

### Steps to reproduce

when firebase is connection established through CLI

### Expected behavior

time out Exception 

### Screenshots

not important

### Additional context and comments

kindly provide me this solution

**Comment by simonpetersgh** [comment]
Hello, I added the firebase_core package, to my pubspec file and issue got
resolved for me.
Try that and see if it works for you.

**Comment by KoamiviKELEDOME** [comment]
> Hi, I have been having this issue for couple of weeks now. Please,  is there a fix?

I'm also having this problem. Did you get a solution?

**Comment by DavidJ19** [comment]
Any updates on a solution as I can't get beyond this issue

**Comment by sinawatra** [comment]
_ Change the baseURL api, sometime it's not fetch from .env files. Other file has that apiBaseUrl or BaseURL too, so change it all in those files too
