### ISSUE TITLE
[bug]:  dSYM file name with spaces causes upload failure in FlutterFire CLI

### ISSUE THREAD

**Issue by smithemely** [invertase/flutterfire_cli#339]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

1.0.1-dev.4

### Firebase Tools version

13.18.0

### Flutter Doctor Output

[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-arm64, locale en-UA)
    • Flutter version 3.24.3 on channel stable at /Users/smem/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (11 days ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/smem/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (2 available)
    • macOS (desktop)                 • macos                 • darwin-arm64 • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin       • macOS 14.6.1 23G93 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

### Description

When using `flutterfire CLI` to configure and build an iOS project with a dSYM that contains a space in its filename, the build process fails during the symbol upload phase. The issue occurs because the `DWARF_DSYM_FILE_NAME` environment variable, which contains a space (e.g., `Custom App.app.dSYM`), is being truncated after the first space. As a result, the upload fails, and the crashlytics symbols are not uploaded correctly.

This behavior has been observed when running the build through GitHub Actions on a self-hosted macOS runner.

### Steps to reproduce

1) Install `flutterfire_cli` by running:
```bash
dart pub global activate flutterfire_cli 1.0.1-dev.4
```
2) Configure the FlutterFire project by running:
```bash
flutterfire configure --project="$project_id" \
   --platforms="ios" \
   --ios-bundle-id="$package_name" \
   --macos-bundle-id="$package_name" \
   --android-package-name="$package_name" \
   --web-app-id="$package_name" \
   --windows-app-id="$package_name" \
   --yes
```
3) Build the iOS app with the following command:
```bash
flutter build ipa --release \
   --build-name=0.0.1 \
   --build-number=0.0.1
```
Observe the error during the symbol upload phase.

### Expected behavior

The build process should correctly handle `DWARF_DSYM_FILE_NAME` values with spaces (e.g., `Custom App.app.dSYM`), ensuring that the entire name is passed to the symbol upload command. This would prevent the crash and allow dSYM files to be uploaded successfully.

### Error message
Here is an example of the error message in the logs:
```less
xxxx-xx-xx xx:xx:xx.xxx upload-symbols[xxxxx:xxxxxxx] Unable to get file attributes for dSYM file at path "/Users/user/Library/Developer/Xcode/DerivedData/Runner-xxxxxxxxxxxxxxxxxxxxxxxxxxxx/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/Custom/Contents/Resources/DWARF"

#0      UploadCrashlyticsSymbols.run (package:flutterfire_cli/src/commands/upload_symbols.dart:406:7)
<asynchronous suspension>
#1      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#2      main (file:///Users/user/.pub-cache/hosted/pub.dev/flutterfire_cli-1.0.1-dev.4/bin/flutterfire.dart:63:5)
<asynchronous suspension>
Command PhaseScriptExecution failed with a nonzero exit code
```
In the error, it's visible that the file name was truncated to `Custom`, instead of the full name `Custom App.app.dSYM`.
### Build phase script
The generated build phase script after running `flutterfire configure` is as follows:
```bash
#!/bin/bash
PATH="${PATH}:$FLUTTER_ROOT/bin:$HOME/.pub-cache/bin"
flutterfire upload-crashlytics-symbols --upload-symbols-script-path="$PODS_ROOT/FirebaseCrashlytics/upload-symbols" --platform=ios --apple-project-path="${SRCROOT}" --env-platform-name="${PLATFORM_NAME}" --env-configuration="${CONFIGURATION}" --env-project-dir="${PROJECT_DIR}" --env-built-products-dir="${BUILT_PRODUCTS_DIR}" --env-dwarf-dsym-folder-path="${DWARF_DSYM_FOLDER_PATH}" --env-dwarf-dsym-file-name="${DWARF_DSYM_FILE_NAME}" --env-infoplist-path="${INFOPLIST_PATH}" --default-config=default
```
All variables are wrapped in quotes, and the project configuration file (`project.pbxproj`) also includes escaped quotes. However, the space is still causing the file name to be truncated.

**Comment by kaciula** [comment]
Also mentioned here: https://github.com/invertase/flutterfire_cli/issues/293
