### ISSUE TITLE
CLI not selecteable on Windows CMD and Powershell

### ISSUE THREAD

**Issue by rayliverified** [invertase/flutterfire_cli#34]
This is how it looks on Cmd. Probably not intended! 

![snap_screen_20220105145719](https://user-images.githubusercontent.com/19896174/148288397-993c612f-9423-437a-8fea-38f6fd142b4c.png)

**Comment by amrh-h** [comment]
same as me.  i also tired it on my friend's laptop and the result was like this

**Comment by russellwheatley** [comment]
Workaround is to select the project you intend to use. Example:
```
flutterfire configure --project=project-name 
```

**Comment by rayliverified** [comment]
With the --yes flag, the workaround is to specify all the configurations in the command prompt.

Closing with workaround.
