### ISSUE TITLE
flutterfire cli not working from VS Code terminal

### ISSUE THREAD

**Issue by mueen-memon** [invertase/flutterfire_cli#38]
I have added the flutterfire cli path into the environment variables on Windows. Still VS Code terminal does not know flutterfire command. Even though it is working in windows cmd.

**Comment by dnadawa** [comment]
Try `flutterfire.bat` instead of `flutterfire`

Eg: `flutterfire.bat configure`

**Comment by anilsapkota** [comment]
I have the same issue. I added path to environment variable as well, but still getting flutterfire cli not working. Tried .bat also but didn't work

**Comment by starlocke** [comment]
I initially had the same problems. Neither `flutterfire` nor `flutterfire.bat` worked, when freshly installed the first time + setting up extra PATH directories.

Eventually, after a system reboot and doing:

- `dart pub global activate flutterfire_cli`
- `flutterfire.bat`

... it just worked.

In a linux-like environment (ex: git-bash), adding an alias helps too. There are multiple ways to accomplish this. One of them is:

- `alias flutterfire=flutterfire.bat`

**Comment by thecannoli** [comment]
> I initially had the same problems. Neither `flutterfire` nor `flutterfire.bat` worked, when freshly installed the first time + setting up extra PATH directories.
> 
> Eventually, after a system reboot and doing:
> 
> * `dart pub global activate flutterfire_cli`
> * `flutterfire.bat`
> 
> ... it just worked.
> 
> In a linux-like environment (ex: git-bash), adding an alias helps too. There are multiple ways to accomplish this. One of them is:
> 
> * `alias flutterfire=flutterfire.bat`

This worked for me 05-01-24 in visual studio code on windows. Thanks!

**Comment by RonmelRoss** [comment]
> I initially had the same problems. Neither `flutterfire` nor `flutterfire.bat` worked, when freshly installed the first time + setting up extra PATH directories.
> 
> Eventually, after a system reboot and doing:
> 
> * `dart pub global activate flutterfire_cli`
> * `flutterfire.bat`
> 
> ... it just worked.
> 
> In a linux-like environment (ex: git-bash), adding an alias helps too. There are multiple ways to accomplish this. One of them is:
> 
> * `alias flutterfire=flutterfire.bat`


The steps above provided by [starlocke](https://github.com/starlocke) also worked for me. I guess we'd have to add the path to environment variable first to before running `dart pub activate` to enable the CLI. Thank you!
