### ISSUE TITLE
[flutterfire_cli] Firebase CLI supports multiple users, while flutterfire CLI only supports one

### ISSUE THREAD

**Issue by dJani97** [invertase/flutterfire_cli#39]
**Describe the bug**

I have initialized FlutterFire in my Flutter project by following the CLI guide at [FlutterFire / docs / CLI](https://firebase.flutter.dev/docs/cli)

I'm logged into multiple Google accounts in the Firebase CLI, and during (and after) initialization I'm unable to select which account I'd like to use for the current Flutter project.

Running `firebase login:use <email>` in the already initialized FlutterFire project fails.

### Steps to reproduce

1. run `flutter create`
2. run `flutterfire configure`
3. add a second Google account to the Firebase CLI using `firebase login:add <email>`
4. try running `firebase login:use <email>` in the project
5. result: `Error: Could not determine active Firebase project directory`

### Expected behavior

I expected Firebase CLI to set the default account to use for this project directory.

Or I would expect `flutterfire configure` to let me decide which Google account I'd like to use when initializing the FlutterFire project.

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.0, on Microsoft Windows [Version 10.0.22000.434], locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Community Edition (version 2021.3)
[✓] VS Code (version 1.45.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

</details>

---

**Comment by subzero911** [comment]
Same here. CLI picks the wrong user. And seems like no way to choose the custom user.

**Comment by Salakar** [comment]
`--account` option has been supported since the first release, please try it out, e.g. `flutterfire --account=foo@bar.com configure`

**Comment by doubleo2** [comment]
@Salakar account is not a global option. It should be `flutterfire configure --account=foo@bar.com`
