### ISSUE TITLE
wrong google user

### ISSUE THREAD

**Issue by subzero911** [invertase/flutterfire_cli#41]
I run `flutterfire configure`
It automatically chooses the user

![image](https://user-images.githubusercontent.com/12999702/155105934-43a430c1-acb7-41e2-b080-fb64f8dfea60.png)

But this user doesn't have access to the Firebase project. So this config utility fails.
I actually need [s.molchanovskiy@notamedia.ru](mailto:s.molchanovskiy@notamedia.ru) as a user. How can I choose the custom user?
I tried to login in Chrome as [s.molchanovskiy@notamedia.ru](mailto:s.molchanovskiy@notamedia.ru) into Firebase, but configuration utility still uses [sergeymolchanovsky@gmail.com](mailto:sergeymolchanovsky@gmail.com) address.

**Comment by mrverdant13** [comment]
This is done by using the `firebase` CLI.

For your specific use case, these are the sub-commands that might be handy:
- `firebase login:list`: logs a list of the registered authorized accounts.
- `firebase login:add [options] <email>`: starts the auth flow to register the `<email>` account locally.
- `firebase login:use <email>`: sets `<email>` as default account.

For more in-depth info about these sub-commands or about the Firebase CLI itself, use `firebase --help`.

**Comment by mrverdant13** [comment]
Hello, @subzero911 

This is done by using the `firebase` CLI.

For your specific use case, these are the sub-commands that might be handy:
- `firebase login:list`: logs a list of the registered authorized accounts.
- `firebase login:add [options] <email>`: starts the auth flow to register the `<email>` account locally.
- `firebase login:use <email>`: sets `<email>` as default account.

For more in-depth info about these sub-commands or about the Firebase CLI itself, use `firebase --help`.

**Comment by Salakar** [comment]
`flutterfire` cli also supports the `--account` option when running commands, e.g.  `flutterfire --acount=foo@bar.com configure`
