### ISSUE TITLE
Is there a way to run flutterfire configure from the command line silently?

### ISSUE THREAD

**Issue by dancamdev** [invertase/flutterfire_cli#48]
My goal here is to run the `flutterfire configure` command in a script, so I need it to run without promting for user input.

I tried passing the following arguments, which matched with me being already logged into the account, I expected to work without user intervention.

`flutterfire configure -p <project-name> -i <ios_app_id> -a <android_app_id>`

But the cli would still prompt me with selecting the platforms. Is there anyway around that? The help section doesn't cover it.

**Comment by Salakar** [comment]
`--yes` flag has just been added for this, e.g. `flutterfire config --project=<projectId> --yes` 

This will be available in the next release. Thanks!

**Comment by shinayser** [comment]
This command has been released but is still not on the documentation page here:
https://firebase.flutter.dev/docs/cli/
