### ISSUE TITLE
[doc] missing documentation link

### ISSUE THREAD

**Issue by iapicca** [invertase/flutterfire_cli#5]
`Documentation` link in [README.md](https://github.com/invertase/flutterfire_cli/blob/main/README.md) 
is broken ![image](https://user-images.githubusercontent.com/45637986/144726565-dae82049-cf37-4fc5-9876-55c4ca8e872b.png)

**Comment by Salakar** [comment]
This is expected since the documentation doesn't go live until later in the week - not promoting the use of the CLI until then
