### ISSUE TITLE
Cannot switch from one google account's firebase projects to another google account's firebase projects

### ISSUE THREAD

**Issue by Zelfapp** [invertase/flutterfire_cli#54]
I have two firebase projects that are in two separate google accounts. Let's call them "a" and "b". 

Following the [FlutterFire CLI instructions](https://firebase.flutter.dev/docs/cli).

From the directory for project "a" I did the following:

1. `flutterfire configure` and signed into google account "a" a@gmail.com.
2. Was able to choose an existing project for "a". No problems.
3. Still in directory "a" I ran `firebase login:add b@gmail.com`, to add my 2nd google account that can be used, and signed in successfully.
4. Then from directory "b" I ran `flutterfire configure --account b@gmail.com`, but I get this error: `FirebaseProjectNotFoundException: Firebase project id "myprojectid" could not be found on this Firebase account.`

I do not see in `flutterfire configure --help` any information on how to switch from one google account to another google account when in a project directory.

There should be a simple way to get projects from the right google account in a project directory. Maybe there is and I'm just missing it or doing something wrong.

I've also [asked this question on SO](https://stackoverflow.com/questions/71803062/flutterfire-cli-how-to-switch-between-separate-firebase-consoles/71818593#71818593).

Also note: If I try to run `firebase --account=b@gmail.com init` rather than `flutterfire configure` I get `Error: HTTP Error: 403, The caller does not have permission`, but my project "b" does exist and I've check IAM and service accounts and they appear to have all the correct permissions.

**Comment by tologonkudaiberdiuulu** [comment]
Any progress?

**Comment by Zelfapp** [comment]
@tologonkudaiberdiuulu 

### ANSWER (for my use case):
If you're having issues switching accounts `firebase projects:list --debug` may very well give you the insight for more difficult issues like mine here.

Using `firebase projects:list --debug` I saw that the authorization was using an ENV `FIREBASE_TOKEN`, which at some point I must have put into my `~/.bashrc`. This token was for project "A". I removed the ENV token and now everything is working as expected.

**Comment by russellwheatley** [comment]
Thanks for letting us know, @Zelfapp. Closing this issue out.
