### ISSUE TITLE
Feature Request: Add a bug report command for FlutterFire issues

### ISSUE THREAD

**Issue by Salakar** [invertase/flutterfire_cli#6]
It'd be nice to have a single command that CLI users can run that outputs all the information required to help with reporting an issue on the FlutterFire repository, e.g. FlutterFire package versions, Dart version, Flutter version, Android build versions, Xcode version, iOS/macOS build target version etc

cc @TahaTesser - maybe you have some things you'd like to see here

**Comment by Ehesp** [comment]
`flutterfire doctor` 👯

**Comment by amit-ksh** [comment]
`flutterfire audit`
Or
`flutterfire inspect`

**Comment by AP2008** [comment]
I would like to work on this

**Comment by werainkhatri** [comment]
fyi: i've already started working on this and will raise a PR by the weekend. not sure what the protocol is (thanks for the CONTRIBUTING.md issue btw).

**Comment by bhattabhi013** [comment]
Hey @werainkhatri,
If you are a maintainer, can you please assign me that issue under hacktoberfest tag?

**Comment by werainkhatri** [comment]
> If you are a maintainer, can you please assign me that issue under hacktoberfest tag?

@bhattabhi013 i am not 😅, just another (soon-to-be 🤞🏾) contributor.
