### ISSUE TITLE
[proposal]:  add a command to explicitly add a Flutter plugin for Firebase and configure it

### ISSUE THREAD

**Issue by Salakar** [invertase/flutterfire_cli#65]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command

`flutterfire add <firebaseFlutterPlugin>`

### Description

This command would add a way to add a Firebase service to your Flutter app and configure it at the same time. 

Internally this command would do the following;

1. `flutter pub add <pluginName>`.
2. Update Firebase configuration (what `flutterfire configure` currently does).
3. In the case of plugins such as `firebase_crashlytics` or `firebase_performance` apply related Android gradle configurations automatically.

### Reasoning

Currently a developer needs to run `configure` multiple times to set up their project ot use a single Firebase product:

1. Run `flutterfire configure`.
2. Run` flutter pub add firebase_core`.
3. Add some Dart code for initialization.
4. Run `flutter pub add firebase_crashlytics`.
5. Run `flutterfire configure` again. (to add Crashlytics' Gradle plugin, but also applies to other products like enabling RTDB)
6. Run `flutter run`.

Adding this command could change the flow to look similar to:

1. Run `flutterfire add firebase_core`.
2. Add some Dart code for initialization.
3. Run `flutterfire add firebase_crashlytics`
4. Run `flutter run`.

### Additional context and comments

Original proposal as suggested by @rachelsaunders.

This however may also technically obsolete `flutterfire configure`?

**Comment by russellwheatley** [comment]
We now have `flutterfire install` to add plugins you desire.
