### ISSUE TITLE
request:  Add support for defaulting to either yes or no (or improve --yes / --skip)

### ISSUE THREAD

**Issue by erf** [invertase/flutterfire_cli#69]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command

flutterfire configure --default no

### Description

I would like to default to yes or no to the various command prompts. 

This is different than the yes / skip argument, which would always use the default value.

### Reasoning

I would like to automate the configure commands in a script and be able to skip user input but use a value other than the default value.

### Additional context and comments

Maybe the -y --yes argument could be changed to -s --skip as "yes" is a bit less descriptive. Even better a -s --skip argument could default to the default value, or you could supply either a "default", "yes" or "no" value after to determine what to choose.

**Comment by russellwheatley** [comment]
I don't think this is an issue on the latest FlutterFire CLI. 
```
dart pub global activate flutterfire_cli 0.3.0-dev.18 --overwrite
```

The only thing `--yes` is used for now is for platform selection. If you choose platforms, it is not needed. Example:
```
flutterfire configure --project=project-name --platforms=android
```
We auto detect the previous things that required the default CLI flag `--yes`.
