### ISSUE TITLE
request:  Make explicit upgrade command

### ISSUE THREAD

**Issue by erf** [invertase/flutterfire_cli#73]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command

flutterfire upgrade

### Description

Add a `flutterfire upgrade` command which upgrades the tool to the latest version (if available).

### Reasoning

I was wondering how to update the **flutterfire CLI** tool and noticed a upgrade prompt after typing **flutterffire version**, maybe there could be an explicit command for this.

**Comment by russellwheatley** [comment]
If you run:
```
dart pub global activate flutterfire_cli
```

It already upgrades to the latest version 👍
