### ISSUE TITLE
request:  Command to fetch app config files (json or dart) without changing existing Firebase

### ISSUE THREAD

**Issue by erf** [invertase/flutterfire_cli#74]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command

flutterfire fetch

### Description

I would like to see a read-only `fetch` command which just fetches existing app configuration in either `dart` or `json` format without changing the existing Firebase project.

### Reasoning

We would like to avoid adding the API Keys to a git repo, so we would like to fetch the API keys after fetching the source code and before building.

I appreciate the way we can generate Dart files now with `flutterfire configure`, but this does optionally change the Firebase project by adding a new app and also involves more user interaction.

I think a more light weight read-only call would be better for fetching API keys from existing apps, without making changes.

I appreciate the generated `dart` classes but i would like to see an option to fetch the `Google-services.json` files for handling this the old way. I'm not aware the Firebase CLI tool (or another way) has an option to do this.

**Comment by russellwheatley** [comment]
The `google-services.json` file does not contain sensitive data, in any event, once you run the `flutterfire configure` command, you can literally copy/paste/delete the file however you wish once it is written in your file system.
