### ISSUE TITLE
request:  Create folders for "out" file

### ISSUE THREAD

**Issue by erf** [invertase/flutterfire_cli#75]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command

flutterfire configure --out=/lib/config/dev/firebase_options.dart

### Description

I would like the `configure --out` command to create the given directories.

### Reasoning

Now it fails if the `out` directory does not exists. I think it would be convenient if it was made.

**Comment by Salakar** [comment]
Shipped in the latest version, thanks again :)
