### ISSUE TITLE
[bug]:  FlutterAppRequiredException: The current directory does not appear to be a Flutter application project.

### ISSUE THREAD

**Issue by exampaqs** [invertase/flutterfire_cli#84]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.2.2+2

### Firebase Tools version

11.1.0

### Flutter Doctor Output

name:
description:

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+6

environment:
sdk: ">=2.12.0 <3.0.0"

dependencies:
auto_size_text: ^3.0.0-nullsafety.0
carousel_slider: ^4.0.0-nullsafety.0
cloud_firestore: ^3.1.6
expandable: ^5.0.1
firebase_auth: ^3.0.1
firebase_core: ^1.1.0
firebase_storage: ^10.0.1
flutter_bloc: ^8.0.1
flutter_countdown_timer: ^4.1.0
flutter_html: ^2.2.1
flutter_svg: ^0.23.0+1
fluttertoast: ^8.0.6
hexcolor: ^2.0.3
http: ^0.13.2
in_app_review: ^2.0.2
math_expressions: ^2.3.0
path_provider: ^2.0.9
percent_indicator: ^4.0.0
provider: ^6.0.2
responsive_grid: ^2.0.0
screenshot: ^ 1.0.0-nullsafety.1
share_plus: ^4.0.3
share_plus_web: ^3.0.0
shared_preferences: ^2.0.5
url_launcher: ^6.0.3
wakelock: ^0.6.1+1
purchases_flutter: ^3.10.0

dev_dependencies:
flutter_test:
sdk: flutter
test: ^1.16.5

flutter:

uses-material-design: true

assets:
- images/favicon.png
- images/exampaq.png

fonts:
- family: greatvibes
fonts:
- asset: fonts/greatvibes.ttf

- family: mrsaints
  fonts:
    - asset: fonts/mrsaints.ttf

# - family: roboto
#   fonts:
#     - asset: fonts/roboto.ttf
- family: redressed
  fonts:
    - asset: fonts/redressed.ttf

- family: shadowsintolight
  fonts:
    - asset: fonts/shadowsintolight.ttf

### Description

The CLI throws FlutterAppRequiredException: The current directory does not appear to be a Flutter application project when I run `flutterfire configure` command

### Steps to reproduce

run `flutterfire configure` command

### Expected behavior

FlutterAppRequiredException: The current directory does not appear to be a Flutter application project.

**Comment by russellwheatley** [comment]
You can only run FlutterFire CLI from within a Flutter project otherwise you get this exception.
