### ISSUE TITLE
Cannot run dart pub global activate flutterfire_cli

### ISSUE THREAD

**Issue by herotha** [invertase/flutterfire_cli#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.0.0

### Firebase Tools version

11.2.2

### Flutter Doctor Output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.1 21C52 darwin-x64, locale en-KH)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.68.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

### Description

Pub failed to run subprocess `chmod`: ProcessException: No such file or directory
  Command: chmod 755 /Users/mac/.pub-cache/_temp/dirTVy9d0/.gitignore

### Steps to reproduce

when I try to run command "dart pub global activate flutterfire_cli"

### Expected behavior

when I try to run command "dart pub global activate flutterfire_cli"

### Screenshots

<img width="585" alt="image" src="https://user-images.githubusercontent.com/8534773/179463601-b68952ef-dc07-4fe2-aeda-61fc511a33aa.png">

**Comment by russellwheatley** [comment]
You likely need to put `some-other-directories/pub-cache/bin` on your path. This isn't a FlutterFire CLI bug.
